package Vista;

import Controlador.ColumnasTablas;
import Modelo.Categoria;
import Modelo.Conexion;
import Modelo.MySQLDAO.CategoriaDAO;
import Modelo.MySQLDAO.ProductoPresentacionDAO;
import Modelo.ProductoPresentacion;
import ModelosTablas.TablaRender;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Grover
 */
public class ConfiguracionPrecios extends javax.swing.JInternalFrame {

    DefaultTableModel modelo;
    int idAlmacen = 2;

    public ConfiguracionPrecios() {
        initComponents();
        Color fondo = new Color(204,204,255);
        Color texto = new Color(51, 51, 51);
        TablaRender ft = new TablaRender(fondo, texto);//color de las celdas
        tblProductos.setDefaultRenderer(Object.class, ft);//setea el color en la tabla
        
        Inicio();
    }

    private void Inicio() {
        try {
            titulosTabla();
            cargarComboCategorias();
            lblBarra.setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBarras = new javax.swing.ButtonGroup();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmbCategoria = new javax.swing.JComboBox<>();
        btnBarraGeneral = new javax.swing.JToggleButton();
        btnBarraVip = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblBarra = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtCodigoProducto = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();

        setClosable(true);
        setTitle("CONFIGURACION DE PRECIOS");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText(".");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 610, 130, -1));

        tblProductos.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProductos.setSelectionForeground(new java.awt.Color(51, 51, 51));
        tblProductos.getTableHeader().setResizingAllowed(false);
        tblProductos.getTableHeader().setReorderingAllowed(false);
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProductos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 200, 690, 580));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("CONFIGURACION DE PRECIOS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, 50));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("PRODUCTOS");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 20, 320, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("categoria");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 70, -1));

        cmbCategoria.setBackground(new java.awt.Color(204, 204, 255));
        cmbCategoria.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbCategoria.setForeground(new java.awt.Color(255, 255, 255));
        cmbCategoria.setBorder(null);
        cmbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoriaActionPerformed(evt);
            }
        });
        jPanel1.add(cmbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 320, -1));

        grupoBarras.add(btnBarraGeneral);
        btnBarraGeneral.setText("BARRA GENERAL");
        btnBarraGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarraGeneralActionPerformed(evt);
            }
        });
        jPanel1.add(btnBarraGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 113, 150, 30));

        grupoBarras.add(btnBarraVip);
        btnBarraVip.setText("BARRA VIP");
        btnBarraVip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarraVipActionPerformed(evt);
            }
        });
        jPanel1.add(btnBarraVip, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 153, 150, 30));

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 810, 10));

        lblBarra.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblBarra.setForeground(new java.awt.Color(255, 51, 51));
        lblBarra.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBarra.setText(".");
        jPanel1.add(lblBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 104, 390, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 320));

        body.setBackground(new java.awt.Color(160, 160, 160));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("producto");
        body.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 80, -1));

        txtProducto.setEditable(false);
        txtProducto.setBackground(new java.awt.Color(160, 160, 160));
        txtProducto.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 24)); // NOI18N
        txtProducto.setForeground(new java.awt.Color(255, 255, 255));
        txtProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtProducto.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        body.add(txtProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 440, -1));

        jLabel9.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("precio");
        body.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 530, 80, -1));

        txtPrecio.setBackground(new java.awt.Color(160, 160, 160));
        txtPrecio.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 24)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(255, 255, 255));
        txtPrecio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPrecio.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        body.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 560, 110, -1));

        btnGuardar.setBackground(new java.awt.Color(204, 204, 255));
        btnGuardar.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 24)); // NOI18N
        btnGuardar.setText("guardar");
        btnGuardar.setBorder(null);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        body.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 550, 140, 40));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("codigo");
        body.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 60, -1));

        txtCodigoProducto.setEditable(false);
        txtCodigoProducto.setBackground(new java.awt.Color(160, 160, 160));
        txtCodigoProducto.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 24)); // NOI18N
        txtCodigoProducto.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigoProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigoProducto.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        txtCodigoProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoProductoKeyPressed(evt);
            }
        });
        body.add(txtCodigoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 80, -1));

        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        body.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, 810, 10));

        getContentPane().add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 820, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseClicked
        int fila = tblProductos.getSelectedRow();
        txtCodigoProducto.setText(tblProductos.getValueAt(fila, 0).toString());
        txtProducto.setText(tblProductos.getValueAt(fila, 1).toString());
        txtPrecio.setText(tblProductos.getValueAt(fila, 3).toString());
    }//GEN-LAST:event_tblProductosMouseClicked

    private void txtCodigoProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoProductoKeyPressed
        String valor = txtCodigoProducto.getText();
        if (!txtCodigoProducto.getText().isEmpty()) {

            for (int i = 0; i < tblProductos.getRowCount(); i++) {
                //vistaConfPrecios.tblProductos.requestFocus();
                tblProductos.changeSelection(tblProductos.getSelectedRow(), 0, false, false);
            }

        } else {
            tblProductos.clearSelection();
        }
    }//GEN-LAST:event_txtCodigoProductoKeyPressed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (!txtCodigoProducto.getText().trim().isEmpty()) {
            try {
                int idProducto = Integer.parseInt(txtCodigoProducto.getText());
                ProductoPresentacionDAO pdao = new ProductoPresentacionDAO();
                ProductoPresentacion pp = new ProductoPresentacion();
                //pp = pdao.obtenerProductoPresentacion(idProducto);
                pp.setPrecio(Double.parseDouble(txtPrecio.getText()));                
                pp.setIdProductoPresentacion(idProducto);
                if (pdao.updatePrecio(pp,idAlmacen)) {
                    JOptionPane.showMessageDialog(getRootPane(), "PRECIO DE " + txtProducto.getText() + " ACTUALIZADO");
                    //LimpiarTabla(tblProductos, modelo);
                    Categoria c = (Categoria)cmbCategoria.getSelectedItem();
                    LlenarTablaBuscarProductos(c.getIdcategoria(), idAlmacen);
                    limpiarCampos();
                }

//                    System.out.println("Stock: " +pp.getStock());
//                    System.out.println("Precio: " +pp.getPrecio());
//                    System.out.println("ProductoPresentacion: " +pp.getIdProductoPresentacion());
            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
        } else {
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void cmbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoriaActionPerformed
        try {
            Categoria c = new Categoria();
            
            c =(Categoria) cmbCategoria.getSelectedItem();
            
            LlenarTablaBuscarProductos(c.getIdcategoria(), idAlmacen);
            
            limpiarCampos();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_cmbCategoriaActionPerformed

    private void btnBarraGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarraGeneralActionPerformed
        idAlmacen = 2;
        try {
            Categoria c =(Categoria) cmbCategoria.getSelectedItem();
            
            LlenarTablaBuscarProductos(c.getIdcategoria(), idAlmacen);
            
            lblBarra.setText("BARRA GENERAL");
            lblBarra.setVisible(true);
            limpiarCampos();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnBarraGeneralActionPerformed

    private void btnBarraVipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarraVipActionPerformed
        idAlmacen = 3;
        try {
            Categoria c =(Categoria) cmbCategoria.getSelectedItem();
            
            LlenarTablaBuscarProductos(c.getIdcategoria(), idAlmacen);
            
            lblBarra.setText("BARRA VIP");
            lblBarra.setVisible(true);
            limpiarCampos();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnBarraVipActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JToggleButton btnBarraGeneral;
    private javax.swing.JToggleButton btnBarraVip;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JComboBox<Categoria> cmbCategoria;
    private javax.swing.ButtonGroup grupoBarras;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblBarra;
    public javax.swing.JTable tblProductos;
    public javax.swing.JTextField txtCodigoProducto;
    public javax.swing.JTextField txtPrecio;
    public javax.swing.JTextField txtProducto;
    // End of variables declaration//GEN-END:variables

    public void titulosTabla() {
        String titulos[] = {"ID", "PRODUCTO", "PRESENTACION", "PRECIO"};
        modelo = new DefaultTableModel(null, titulos);
        tblProductos.setModel(modelo);
    }

    public void LlenarTablaBuscarProductos(int idCategoria, int idWarehouse) throws Exception {
        titulosTabla();
        Conexion con = new Conexion();
        try {
            con.conectar();

            String sql = "select productopresentacion.idproductopresentacion, producto.nombre, presentacion.descripcion, productopresentacion.precio\n"
                    + "	from producto \n"
                    + "	inner join productopresentacion on producto.idproducto = productopresentacion.idproducto\n"
                    + "	inner join presentacion on productopresentacion.idpresentacion = presentacion.idpresentacion\n"
                    + "	inner join categoria on productopresentacion.idcategoria = categoria.idcategoria\n"
                    + "	where categoria.idcategoria = " + idCategoria + "  AND productopresentacion.idalmacen = "+idWarehouse+" \n"
                    + "	order by productopresentacion.idproductopresentacion;";

            PreparedStatement pst = con.getConexion().prepareStatement(sql);

            ResultSet res = pst.executeQuery();

            Object[] datos = new Object[4];

            while (res.next()) {
                datos[0] = res.getInt(1);
                datos[1] = res.getString(2);
                datos[2] = res.getString(3);
                datos[3] = res.getDouble(4);
                modelo.addRow(datos);
            }

            tblProductos.setModel(modelo);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error " + e.getMessage());
        } finally {
            con.cerrar();
        }
        new ColumnasTablas().cuatroColumnas(tblProductos, 50, 200,50,50);
    }

    private void LimpiarTabla(JTable tabla, DefaultTableModel modelo) {
        for (int i = 0; i < tabla.getRowCount(); i++) {
            modelo.removeRow(i);
            i -= 1;
        }
    }

    public void limpiarCampos() {
        txtCodigoProducto.setText("");
        txtPrecio.setText("");
        txtProducto.setText("");
    }

    public void cargarComboCategorias() throws Exception {
        CategoriaDAO cdao = new CategoriaDAO();
        for (Categoria c : cdao.Listar()) {
            cmbCategoria.addItem(c);
        }
    }

}
