/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.InventarioValorizadoControl;

/**
 *
 * @author MARCEL
 */
public class InventarioValorizado extends javax.swing.JInternalFrame {

    /**
     * Creates new form InventarioValorizado
     */
    public InventarioValorizado() throws Exception {
        initComponents();
        datosIniciales();
    }

    public void datosIniciales() throws Exception {
        try {
            new InventarioValorizadoControl().cabecera(tblInventario);
            new InventarioValorizadoControl().llenarTabla(tblInventario);
            txtValorizacion.setText(""+calcularValorizacionTotal());
            grupoRadio.add(rbStock);
            grupoRadio.add(rbCodigo);
            grupoRadio.add(rbProducto);
            grupoRadio.add(rbCategoria);
        } catch (Exception e) {
            e.getMessage();
        }

    }

    public double calcularValorizacionTotal() {
        double monto = 0;
        for (int i = 0; i < tblInventario.getRowCount(); i++) {
            monto += Double.parseDouble(tblInventario.getValueAt(i, 6).toString());
        }
        return monto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoRadio = new javax.swing.ButtonGroup();
        footer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rbStock = new javax.swing.JRadioButton();
        rbCodigo = new javax.swing.JRadioButton();
        rbProducto = new javax.swing.JRadioButton();
        rbCategoria = new javax.swing.JRadioButton();
        lblRegistros = new javax.swing.JLabel();
        txtValorizacion = new javax.swing.JTextField();
        btnImprimir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtBuscarProducto = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventario = new javax.swing.JTable();

        setClosable(true);
        setTitle("INVENTARIO VALORIZADO (SOLES)");
        setPreferredSize(new java.awt.Dimension(1553, 973));

        footer.setBackground(new java.awt.Color(204, 204, 204));
        footer.setPreferredSize(new java.awt.Dimension(894, 80));
        footer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 24)); // NOI18N
        jLabel1.setText("Buscar");
        footer.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        rbStock.setBackground(new java.awt.Color(204, 204, 204));
        rbStock.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 24)); // NOI18N
        rbStock.setText("stock");
        footer.add(rbStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, -1, -1));

        rbCodigo.setBackground(new java.awt.Color(204, 204, 204));
        rbCodigo.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 24)); // NOI18N
        rbCodigo.setText("código");
        footer.add(rbCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        rbProducto.setBackground(new java.awt.Color(204, 204, 204));
        rbProducto.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 24)); // NOI18N
        rbProducto.setText("producto");
        footer.add(rbProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        rbCategoria.setBackground(new java.awt.Color(204, 204, 204));
        rbCategoria.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 24)); // NOI18N
        rbCategoria.setText("categoria");
        footer.add(rbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        lblRegistros.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 24)); // NOI18N
        lblRegistros.setText("_____________");
        footer.add(lblRegistros, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 40, -1, -1));

        txtValorizacion.setBackground(new java.awt.Color(204, 204, 204));
        txtValorizacion.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 36)); // NOI18N
        txtValorizacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        footer.add(txtValorizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, 180, 60));

        btnImprimir.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        btnImprimir.setText("imprimir");
        footer.add(btnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 10, 120, 60));

        jLabel3.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 24)); // NOI18N
        jLabel3.setText("ordernar por");
        footer.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 30));

        jLabel4.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 24)); // NOI18N
        jLabel4.setText("VALORIZACIÓN");
        footer.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 24)); // NOI18N
        jLabel5.setText("total registros");
        footer.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, -1, -1));

        txtBuscarProducto.setBackground(new java.awt.Color(204, 204, 204));
        txtBuscarProducto.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 24)); // NOI18N
        footer.add(txtBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 210, -1));

        btnBuscar.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        btnBuscar.setText("buscar");
        footer.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 40, -1, -1));

        getContentPane().add(footer, java.awt.BorderLayout.PAGE_END);

        tblInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblInventario);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(InventarioValorizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(InventarioValorizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(InventarioValorizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(InventarioValorizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new InventarioValorizado().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JPanel footer;
    private javax.swing.ButtonGroup grupoRadio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRegistros;
    private javax.swing.JRadioButton rbCategoria;
    private javax.swing.JRadioButton rbCodigo;
    private javax.swing.JRadioButton rbProducto;
    private javax.swing.JRadioButton rbStock;
    private javax.swing.JTable tblInventario;
    private javax.swing.JTextField txtBuscarProducto;
    private javax.swing.JTextField txtValorizacion;
    // End of variables declaration//GEN-END:variables
}
