/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Conexion;
import Controlador.ManejadorFechas;
import Modelo.Movimiento;
import Modelo.MovimientoProducto;
import Modelo.MySQLDAO.MovimientoDAO;
import Modelo.MySQLDAO.MovimientoProductoDAO;
import Modelo.MySQLDAO.PresentacionDAO;
import Modelo.MySQLDAO.ProductoDAO;
import Modelo.MySQLDAO.ProductoPresentacionDAO;
import Modelo.MySQLDAO.UsuarioDAO;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gaby
 */
public class KardexIngresos extends javax.swing.JInternalFrame {

    Conexion con = new Conexion();
    Connection cc = null;

    DefaultTableModel modelProductoIngreso;
    DefaultTableModel modelAddIngreso;

    public KardexIngresos(String usuario) throws Exception {
        initComponents();
        con.conectar();
        cc = con.getConexion();
        txtFechaEntrada.setText(new ManejadorFechas().getFechaActual());
        txtUsuario.setText(usuario);
        titulosProductosIngreso();
        titulosAddIngreso();

    }

    public void titulosProductosIngreso() {
        String[] titulos = {"#ID", "PRODUCTO", "PRESENTACION", "STOCK ACTUAL", "PRECIO"};
        modelProductoIngreso = new DefaultTableModel(null, titulos);
        tblProductoIngreso.setModel(modelProductoIngreso);
    }

    public void titulosAddIngreso() {
        String[] titulos = {"#ID", "PRODUCTO", "PRESENTACION", "CANTIDAD", "CONCEPTO", "SUBTOTAL"};
        modelAddIngreso = new DefaultTableModel(null, titulos);
        tblAddIgresos.setModel(modelAddIngreso);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ingresos = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        txtIngresoProducto = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProductoIngreso = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        txtFechaEntrada = new javax.swing.JTextField();
        btnAddIngreso = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblAddIgresos = new javax.swing.JTable();
        jPanel15 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        txtCantidadIngreso = new javax.swing.JTextField();
        btnRegistrarIngreso = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        txaObservacion = new javax.swing.JTextArea();
        btnQuitarAddIngreso = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("MOVIMIENTOS DE ALMACEN");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ingresos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(51, 102, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("PRODUCTO");
        jPanel10.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        ingresos.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 120, 30));

        txtIngresoProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIngresoProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIngresoProductoKeyReleased(evt);
            }
        });
        ingresos.add(txtIngresoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 330, 30));

        tblProductoIngreso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblProductoIngreso);

        ingresos.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 960, 180));

        jPanel11.setBackground(new java.awt.Color(51, 102, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("FECHA");
        jPanel11.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        ingresos.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 60, 20));

        txtFechaEntrada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ingresos.add(txtFechaEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 20, 100, -1));

        btnAddIngreso.setText("AGREGAR");
        btnAddIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddIngresoActionPerformed(evt);
            }
        });
        ingresos.add(btnAddIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 390, 270, 30));

        tblAddIgresos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tblAddIgresos);

        ingresos.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 960, 190));

        jPanel15.setBackground(new java.awt.Color(51, 102, 255));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("CONCEPTO");
        jPanel15.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, -1, -1));

        ingresos.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 510, 20));

        jPanel16.setBackground(new java.awt.Color(51, 102, 255));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("UNIDADES");
        jPanel16.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        ingresos.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 150, 20));

        txtCantidadIngreso.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtCantidadIngreso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ingresos.add(txtCantidadIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 150, 50));

        btnRegistrarIngreso.setText("REGISTRAR INGRESO");
        btnRegistrarIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarIngresoActionPerformed(evt);
            }
        });
        ingresos.add(btnRegistrarIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 630, 270, 30));

        txaObservacion.setColumns(20);
        txaObservacion.setRows(5);
        jScrollPane9.setViewportView(txaObservacion);

        ingresos.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 510, 90));

        btnQuitarAddIngreso.setBackground(new java.awt.Color(204, 0, 0));
        btnQuitarAddIngreso.setForeground(new java.awt.Color(255, 255, 255));
        btnQuitarAddIngreso.setText("X");
        btnQuitarAddIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarAddIngresoActionPerformed(evt);
            }
        });
        ingresos.add(btnQuitarAddIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 70, -1));

        getContentPane().add(ingresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 690));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("MOVIMIENTOS : INGRESOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 240, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIngresoProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIngresoProductoKeyReleased
        try {
            buscarProductoIngreso();
        } catch (Exception ex) {
            Logger.getLogger(KardexIngresos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtIngresoProductoKeyReleased

    private void btnAddIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddIngresoActionPerformed
        int fila = tblProductoIngreso.getSelectedRow();
            if (!txtCantidadIngreso.getText().trim().isEmpty()) {
                if (!txaObservacion.getText().trim().isEmpty()) {
                    
                    String id = tblProductoIngreso.getValueAt(fila, 0).toString();
                    String prod = tblProductoIngreso.getValueAt(fila, 1).toString();
                    String presentacion = tblProductoIngreso.getValueAt(fila, 2).toString();
                    Double cant = Double.parseDouble(txtCantidadIngreso.getText());
                    String concepto = txaObservacion.getText();
                    double subtotal = cant * (Double.parseDouble(tblProductoIngreso.getValueAt(fila, 4).toString()));

                    if (Integer.parseInt(tblProductoIngreso.getValueAt(fila, 3).toString()) >= cant) {
                        String datos[] = new String[6];
                        datos[0] = id;
                        datos[1] = prod;
                        datos[2] = presentacion;
                        datos[3] = String.valueOf(cant);
                        datos[4] = concepto;
                        datos[5] = String.valueOf(subtotal);

                        modelAddIngreso.addRow(datos);
                        tblAddIgresos.setModel(modelAddIngreso);
                    } else {
                        JOptionPane.showMessageDialog(getRootPane(), "NO SE CUENTA CON LAS UNIDADES REQUERIDAS");
                    }
                    
                } else {
                    JOptionPane.showMessageDialog(getRootPane(), "INGRESE CONCEPTO DE INGRESO");
                }
            } else {
                JOptionPane.showMessageDialog(getRootPane(), "INGRESE CANTIDAD");
            }

    }//GEN-LAST:event_btnAddIngresoActionPerformed

    private void btnRegistrarIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarIngresoActionPerformed
try {
            int numFilas = tblAddIgresos.getRowCount();
            Movimiento m = new Movimiento();
            m.setFecha(new ManejadorFechas().getFechaActualMySQL());
            m.setHora(new ManejadorFechas().getHoraActual());
            m.setIdtipoMovimiento(1);// tipo de movimiento 1 = entradas ; tipo mov 2 = salidas;
            m.setIdUsuario(new UsuarioDAO().getIdUsuario(txtUsuario.getText()));
            m.setObservacion(txaObservacion.getText());
            
            if (new MovimientoDAO().Registrar(m)) {
                System.out.println("MOVIMIENTO REGISTRADO");
                int ultimoMovimiento = new MovimientoDAO().getUltimoMovimiento();
                //ACTUALIZANDO EL STOCK
                int c = 0;
                for (int i = 0; i < numFilas; i++) {
                    MovimientoProducto mp = new MovimientoProducto();
                    mp.setIdMovimiento(ultimoMovimiento);
                    System.out.println("ultimo movimiento: "+ultimoMovimiento);
                    mp.setIdProducto(new ProductoDAO().getIdProducto(Integer.parseInt(tblAddIgresos.getValueAt(i, 0).toString())));
                    System.out.println("idproducto: "+mp.getIdProducto());
                    mp.setIdPresentacion(new PresentacionDAO().getIdPresentacion(tblAddIgresos.getValueAt(i, 2).toString()));
                    System.out.println("idpresentacion: "+mp.getIdPresentacion());
                    mp.setCantidad(Double.parseDouble(tblAddIgresos.getValueAt(i, 3).toString()));
                    System.out.println("cantidad: "+mp.getCantidad());
                    mp.setValorizacion(Double.parseDouble(tblAddIgresos.getValueAt(i, 5).toString()));
                    System.out.println("valorizacion: "+mp.getValorizacion());

                    sumarStock();
                    if (new MovimientoProductoDAO().Registrar(mp)) {
                        c++;
                    }
                }
                if (c > 0) {
                    JOptionPane.showMessageDialog(getRootPane(), "MOVIMIENTO REGISTRADO");
                }
            } else {
                System.out.println("error");
            }

        } catch (Exception e) {
            System.out.println(e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnRegistrarIngresoActionPerformed

    private void btnQuitarAddIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarAddIngresoActionPerformed
        int fila = tblAddIgresos.getSelectedRow();
        modelAddIngreso.removeRow(fila);
    }//GEN-LAST:event_btnQuitarAddIngresoActionPerformed

    public void buscarProductoIngreso() throws Exception {
        Conexion c = new Conexion();
        c.conectar();
        Connection con = c.getConexion();
        limpiarTablaProductoIngresos();
        String art = txtIngresoProducto.getText();
        String datos[] = new String[5];
        String sql = "SELECT productopresentacion.idproductopresentacion, producto.nombre, presentacion.descripcion, productopresentacion.stock, productopresentacion.precio\n"
                + "FROM producto\n"
                + "inner join productopresentacion on producto.idproducto = productopresentacion.idproducto\n"
                + "inner join presentacion on productopresentacion.idpresentacion = presentacion.idpresentacion\n"
                + "where producto.nombre like '" + art + "%' or producto.nombre like '%" + art + "'\n"
                + "order by idproductopresentacion";
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                datos[0] = String.valueOf(rs.getInt("productopresentacion.idproductopresentacion"));
                datos[1] = rs.getString("producto.nombre");
                datos[2] = rs.getString("presentacion.descripcion");
                datos[3] = rs.getString("productopresentacion.stock");
                datos[4] = rs.getString("productopresentacion.precio");
                modelProductoIngreso.addRow(datos);
            }
            tblProductoIngreso.setModel(modelProductoIngreso);
            //tbl_productos.setModel(new DefaultTableModel());
            st.close();
            rs.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(getRootPane(), e.getMessage());
        }finally{
            c.cerrar();
        }
    }

    public void limpiarTablaProductoIngresos() {
        for (int i = 0; i < tblProductoIngreso.getRowCount(); i++) {
            modelProductoIngreso.removeRow(i);
            i -= 1;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddIngreso;
    private javax.swing.JButton btnQuitarAddIngreso;
    private javax.swing.JButton btnRegistrarIngreso;
    private javax.swing.JPanel ingresos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable tblAddIgresos;
    private javax.swing.JTable tblProductoIngreso;
    private javax.swing.JTextArea txaObservacion;
    private javax.swing.JTextField txtCantidadIngreso;
    private javax.swing.JTextField txtFechaEntrada;
    private javax.swing.JTextField txtIngresoProducto;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    private void sumarStock() throws Exception {
        Conexion c = new Conexion();
        c.conectar();
        Connection con = c.getConexion();
        int numFilas = tblAddIgresos.getRowCount();
        try {
            Statement st = null;
            for (int i = 0; i < numFilas; i++) {
                int id = Integer.parseInt(tblAddIgresos.getValueAt(i, 0).toString());
                System.out.println("id: " + id);
                double cantidad = Double.parseDouble(tblAddIgresos.getValueAt(i, 3).toString());
                System.out.println("cantidad: " + cantidad);
                double stock = new ProductoPresentacionDAO().obtenerProductoPresentacion(id).getStock();
                System.out.println("stock: " + stock);
                double newStock = stock + cantidad;
                System.out.println("stock: " + newStock);

                String sql = "UPDATE `productopresentacion` SET `stock`=" + newStock + " WHERE `idproductopresentacion` = " + id + " ";
                st = con.createStatement();
                int rs = st.executeUpdate(sql);
                if (rs > 0) {
                    System.out.println("Se actualizo en stock del producto :" + id);
                }
            }
            st.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            c.cerrar();
        }
    }
}
