/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ImagenFondo;
import Modelo.MySQLDAO.CategoriaDAO;
import Modelo.MySQLDAO.ComprobanteDAO;
import Modelo.MySQLDAO.PerfilDAO;
import Modelo.MySQLDAO.ProductoDAO;
import Modelo.MySQLDAO.TipoComprobanteDAO;
import java.awt.Color;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Gaby
 */
public class MenuPrincipal extends javax.swing.JFrame {

    boolean area, user, perfil, permisos, configuracion, asistencias, trabajadores, mantenimiento, pagos,
            clientes, puntoVenta, reportes, mantVentas, ordenCompra, pendientes, proveedores, contactos, gestionAlmacen, categorias,
            productos, insumos, movimientos, comprobantes, tipoComprobante, apertura, cierre, gastos, flujoCaja;

    public MenuPrincipal(String usuario) throws Exception {
        initComponents();
        area = perfil = user = false;
        setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);
        logo();
        lblUsuario.setText(usuario);
        escritorio.setBorder(new ImagenFondo());
    }

    public void logo() {
        Toolkit tk = Toolkit.getDefaultToolkit();
        setIconImage(tk.getImage(getClass().getResource("/img/party1.png")));
    }

    public MenuPrincipal() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAsistencias = new javax.swing.JButton();
        btnPagos = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnPerfiles = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblCerrarSesion = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        btnPermisos = new javax.swing.JButton();
        btnConfiguracion = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnClientes = new javax.swing.JButton();
        btnMantenimientoVentas = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnPendientes = new javax.swing.JButton();
        btnOrdenCompra = new javax.swing.JButton();
        btnProveedores = new javax.swing.JButton();
        btnContactos = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnGestionAlmacenes = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnCategorias = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        escritorio = new javax.swing.JDesktopPane();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnFlujoCaja = new javax.swing.JButton();
        btnGastos = new javax.swing.JButton();
        btnCierre = new javax.swing.JButton();
        btnComprobantes = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnTipoComprobantes = new javax.swing.JButton();
        btnMovimientos = new javax.swing.JButton();
        btnInsumos = new javax.swing.JButton();
        btnPresentaciones = new javax.swing.JButton();
        btnMedidas = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MR. JUERGA SYSTEM");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lista.png"))); // NOI18N
        jLabel1.setText("PERSONAL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 210, 30));

        btnAsistencias.setBackground(new java.awt.Color(255, 255, 255));
        btnAsistencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/asistencia.png"))); // NOI18N
        btnAsistencias.setText("            ASISTENCIAS");
        btnAsistencias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAsistencias.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnAsistencias.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAsistencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAsistenciasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAsistenciasMouseExited(evt);
            }
        });
        getContentPane().add(btnAsistencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 240, 220, -1));

        btnPagos.setBackground(new java.awt.Color(255, 255, 255));
        btnPagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cartera.png"))); // NOI18N
        btnPagos.setText("                        PAGOS");
        btnPagos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPagos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnPagos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPagosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPagosMouseExited(evt);
            }
        });
        getContentPane().add(btnPagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 275, 220, -1));

        btnUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        btnUsuarios.setText("                 USUARIOS");
        btnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUsuariosMouseExited(evt);
            }
        });
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 65, 220, -1));

        btnPerfiles.setBackground(new java.awt.Color(255, 255, 255));
        btnPerfiles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/perfiles.png"))); // NOI18N
        btnPerfiles.setText("                    PERFILES");
        btnPerfiles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPerfiles.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnPerfiles.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPerfiles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPerfilesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPerfilesMouseExited(evt);
            }
        });
        btnPerfiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilesActionPerformed(evt);
            }
        });
        getContentPane().add(btnPerfiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 100, 220, -1));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCerrarSesion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        lblCerrarSesion.setText("CERRAR SESION");
        lblCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseClicked(evt);
            }
        });
        jPanel2.add(lblCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 10, -1, -1));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("SISTEMA MISTER JUERGA HUANCAYO");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 255, 204));
        jLabel12.setText("USUARIO");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 5, -1, -1));

        lblUsuario.setBackground(new java.awt.Color(255, 255, 255));
        lblUsuario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(204, 255, 204));
        lblUsuario.setText(".......................");
        jPanel2.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 5, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 1500, 30));

        btnPermisos.setBackground(new java.awt.Color(255, 255, 255));
        btnPermisos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/permisos.png"))); // NOI18N
        btnPermisos.setText("                  PERMISOS");
        btnPermisos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPermisos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnPermisos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPermisos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPermisosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPermisosMouseExited(evt);
            }
        });
        getContentPane().add(btnPermisos, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 135, 220, -1));

        btnConfiguracion.setBackground(new java.awt.Color(255, 255, 255));
        btnConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/configuracion.png"))); // NOI18N
        btnConfiguracion.setText("       CONFIGURACION");
        btnConfiguracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfiguracion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnConfiguracion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConfiguracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConfiguracionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConfiguracionMouseExited(evt);
            }
        });
        btnConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiguracionActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 170, 220, -1));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lista.png"))); // NOI18N
        jLabel5.setText("VENTAS");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 210, 30));

        btnClientes.setBackground(new java.awt.Color(255, 255, 255));
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/telemarketer.png"))); // NOI18N
        btnClientes.setText("                    CLIENTES");
        btnClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClientes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClientesMouseExited(evt);
            }
        });
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        getContentPane().add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 340, 220, -1));

        btnMantenimientoVentas.setBackground(new java.awt.Color(255, 255, 255));
        btnMantenimientoVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/llave.png"))); // NOI18N
        btnMantenimientoVentas.setText("       MANTENIMIENTO");
        btnMantenimientoVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMantenimientoVentas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnMantenimientoVentas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMantenimientoVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMantenimientoVentasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMantenimientoVentasMouseExited(evt);
            }
        });
        getContentPane().add(btnMantenimientoVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 445, 220, -1));

        btnReportes.setBackground(new java.awt.Color(255, 255, 255));
        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/periodico.png"))); // NOI18N
        btnReportes.setText("                  REPORTES");
        btnReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReportes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnReportes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportesMouseExited(evt);
            }
        });
        getContentPane().add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 410, 220, -1));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lista.png"))); // NOI18N
        jLabel6.setText("COMPRAS");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 210, 30));

        btnPendientes.setBackground(new java.awt.Color(255, 255, 255));
        btnPendientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lista-pendiente.png"))); // NOI18N
        btnPendientes.setText("              PENDIENTES");
        btnPendientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPendientes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnPendientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPendientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPendientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPendientesMouseExited(evt);
            }
        });
        btnPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPendientesActionPerformed(evt);
            }
        });
        getContentPane().add(btnPendientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 615, 220, -1));

        btnOrdenCompra.setBackground(new java.awt.Color(255, 255, 255));
        btnOrdenCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carro-de-la-compra.png"))); // NOI18N
        btnOrdenCompra.setText("  ORDEN DE COMPRA");
        btnOrdenCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOrdenCompra.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnOrdenCompra.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOrdenCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOrdenCompraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOrdenCompraMouseExited(evt);
            }
        });
        btnOrdenCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenCompraActionPerformed(evt);
            }
        });
        getContentPane().add(btnOrdenCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 510, 220, -1));

        btnProveedores.setBackground(new java.awt.Color(255, 255, 255));
        btnProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/camion-proveedor.png"))); // NOI18N
        btnProveedores.setText("          PROVEEDORES");
        btnProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProveedores.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnProveedores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProveedoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProveedoresMouseExited(evt);
            }
        });
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });
        getContentPane().add(btnProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 545, 220, -1));

        btnContactos.setBackground(new java.awt.Color(255, 255, 255));
        btnContactos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guia-telefonica.png"))); // NOI18N
        btnContactos.setText("               CONTACTOS");
        btnContactos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContactos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnContactos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnContactos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnContactosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnContactosMouseExited(evt);
            }
        });
        btnContactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContactosActionPerformed(evt);
            }
        });
        getContentPane().add(btnContactos, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 580, 220, -1));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lista.png"))); // NOI18N
        jLabel7.setText("ALMACEN");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 210, 30));

        btnGestionAlmacenes.setBackground(new java.awt.Color(255, 255, 255));
        btnGestionAlmacenes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/capital.png"))); // NOI18N
        btnGestionAlmacenes.setText("               ALMACENES");
        btnGestionAlmacenes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGestionAlmacenes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnGestionAlmacenes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGestionAlmacenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGestionAlmacenesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGestionAlmacenesMouseExited(evt);
            }
        });
        btnGestionAlmacenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionAlmacenesActionPerformed(evt);
            }
        });
        getContentPane().add(btnGestionAlmacenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 690, 220, -1));

        btnProductos.setBackground(new java.awt.Color(255, 255, 255));
        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/codigo-de-barras.png"))); // NOI18N
        btnProductos.setText("              PRODUCTOS");
        btnProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProductos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnProductos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProductosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProductosMouseExited(evt);
            }
        });
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        getContentPane().add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 725, 220, -1));

        btnCategorias.setBackground(new java.awt.Color(255, 255, 255));
        btnCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2-rectangulos.png"))); // NOI18N
        btnCategorias.setText("             CATEGORIAS");
        btnCategorias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCategorias.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnCategorias.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCategoriasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCategoriasMouseExited(evt);
            }
        });
        btnCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriasActionPerformed(evt);
            }
        });
        getContentPane().add(btnCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 760, 220, -1));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lista.png"))); // NOI18N
        jLabel8.setText("CONTABLE");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 30, 210, 30));

        escritorio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Bauhaus 93", 0, 65)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 51, 0));
        jLabel13.setText("DISCOTECK");

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Bauhaus 93", 0, 65)); // NOI18N
        jLabel11.setText("DISCOTECK");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/partyBanner.png"))); // NOI18N

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Bauhaus 93", 0, 65)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("MISTER JUERGA");

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Bauhaus 93", 0, 65)); // NOI18N
        jLabel4.setText("MISTER JUERGA");

        escritorio.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                .addContainerGap(549, Short.MAX_VALUE)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel4))
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jLabel13))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(jLabel11))
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel15)))
                .addGap(62, 62, 62))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel4))
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel13))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel11))
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel15)))
                .addContainerGap(685, Short.MAX_VALUE))
        );

        getContentPane().add(escritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 1290, 985));

        btnFlujoCaja.setBackground(new java.awt.Color(255, 255, 255));
        btnFlujoCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/datafono.png"))); // NOI18N
        btnFlujoCaja.setText("        FLUJO DE CAJA");
        btnFlujoCaja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFlujoCaja.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnFlujoCaja.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFlujoCaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFlujoCajaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFlujoCajaMouseExited(evt);
            }
        });
        btnFlujoCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlujoCajaActionPerformed(evt);
            }
        });
        getContentPane().add(btnFlujoCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 200, 220, -1));

        btnGastos.setBackground(new java.awt.Color(255, 255, 255));
        btnGastos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mano-sosteniendo-billetes-de-dinero.png"))); // NOI18N
        btnGastos.setText("                      GASTOS");
        btnGastos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGastos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnGastos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGastos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGastosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGastosMouseExited(evt);
            }
        });
        btnGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGastosActionPerformed(evt);
            }
        });
        getContentPane().add(btnGastos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 160, 220, -1));

        btnCierre.setBackground(new java.awt.Color(255, 255, 255));
        btnCierre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/contabilidad.png"))); // NOI18N
        btnCierre.setText("             CIERRE CAJA");
        btnCierre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCierre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnCierre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCierre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCierreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCierreMouseExited(evt);
            }
        });
        btnCierre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCierreActionPerformed(evt);
            }
        });
        getContentPane().add(btnCierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 130, 220, -1));

        btnComprobantes.setBackground(new java.awt.Color(255, 255, 255));
        btnComprobantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/comprobar.png"))); // NOI18N
        btnComprobantes.setText("      COMPROBANTES");
        btnComprobantes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnComprobantes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnComprobantes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnComprobantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnComprobantesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnComprobantesMouseExited(evt);
            }
        });
        btnComprobantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprobantesActionPerformed(evt);
            }
        });
        getContentPane().add(btnComprobantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 60, 220, -1));

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lista.png"))); // NOI18N
        jLabel9.setText("SISTEMA");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 30));

        btnTipoComprobantes.setBackground(new java.awt.Color(255, 255, 255));
        btnTipoComprobantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/recepcion.png"))); // NOI18N
        btnTipoComprobantes.setText("           DOCUMENTOS");
        btnTipoComprobantes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTipoComprobantes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnTipoComprobantes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTipoComprobantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTipoComprobantesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTipoComprobantesMouseExited(evt);
            }
        });
        btnTipoComprobantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoComprobantesActionPerformed(evt);
            }
        });
        getContentPane().add(btnTipoComprobantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 100, 220, 30));

        btnMovimientos.setBackground(new java.awt.Color(255, 255, 255));
        btnMovimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/equipaje.png"))); // NOI18N
        btnMovimientos.setText("           MOVIMIENTOS");
        btnMovimientos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMovimientos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnMovimientos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMovimientos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMovimientosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMovimientosMouseExited(evt);
            }
        });
        btnMovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovimientosActionPerformed(evt);
            }
        });
        getContentPane().add(btnMovimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 900, 220, -1));

        btnInsumos.setBackground(new java.awt.Color(255, 255, 255));
        btnInsumos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cocina.png"))); // NOI18N
        btnInsumos.setText("                    INSUMOS");
        btnInsumos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInsumos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnInsumos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnInsumos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInsumosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInsumosMouseExited(evt);
            }
        });
        btnInsumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsumosActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsumos, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 830, 220, -1));

        btnPresentaciones.setBackground(new java.awt.Color(255, 255, 255));
        btnPresentaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/storyboard.png"))); // NOI18N
        btnPresentaciones.setText("      PRESENTACIONES");
        btnPresentaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPresentaciones.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnPresentaciones.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPresentaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPresentacionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPresentacionesMouseExited(evt);
            }
        });
        btnPresentaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPresentacionesActionPerformed(evt);
            }
        });
        getContentPane().add(btnPresentaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 795, 220, -1));

        btnMedidas.setBackground(new java.awt.Color(255, 255, 255));
        btnMedidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/metro.png"))); // NOI18N
        btnMedidas.setText("                    MEDIDAS");
        btnMedidas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMedidas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnMedidas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMedidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMedidasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMedidasMouseExited(evt);
            }
        });
        btnMedidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedidasActionPerformed(evt);
            }
        });
        getContentPane().add(btnMedidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 865, 220, -1));

        jButton1.setText("CAJAS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1600, 240, -1, -1));

        jButton2.setText("PAGOS PERSONAL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, 270, -1, -1));

        jButton3.setText("PROMOCIONES");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 950, -1, -1));

        jButton4.setText("reportes");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        try {
            //VERIFICAR SI EXISTEN PERFILES REGISTRADOS
            PerfilDAO pdao = new PerfilDAO();
            if (pdao.Listar().size() > 0) {
                Usuarios u = new Usuarios(lblUsuario.getText());
                escritorio.add(u);
                u.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(rootPane, "DEBE REGISTRAR PERFILES DE USUARIO PARA REGISTRAR USUARIOS");
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnPerfilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilesActionPerformed
        try {
            String usuario = lblUsuario.getText();
            Perfiles p = new Perfiles(usuario);
            escritorio.add(p);
            p.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnPerfilesActionPerformed

    private void btnOrdenCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenCompraActionPerformed
        try {
            String usuario = lblUsuario.getText();
            RegistroCompras oc = new RegistroCompras(usuario);
            escritorio.add(oc);
            oc.setVisible(true);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnOrdenCompraActionPerformed

    private void btnComprobantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprobantesActionPerformed
        try {
            String usuario = lblUsuario.getText();
            Comprobantes c = new Comprobantes(usuario);
            escritorio.add(c);
            c.setVisible(true);

        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }

    }//GEN-LAST:event_btnComprobantesActionPerformed

    private void btnFlujoCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlujoCajaActionPerformed
        String usuario = lblUsuario.getText();
        FujosDeCaja fc = new FujosDeCaja(usuario);
        escritorio.add(fc);
        fc.setVisible(true);
    }//GEN-LAST:event_btnFlujoCajaActionPerformed

    private void btnConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguracionActionPerformed
        String usuario = lblUsuario.getText();
        Configuracion c = new Configuracion(usuario);
        escritorio.add(c);
        c.setVisible(true);
    }//GEN-LAST:event_btnConfiguracionActionPerformed

    private void lblCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseClicked
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_lblCerrarSesionMouseClicked

    private void btnPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPendientesActionPerformed
        OrdenDeCompraPendiente odcp = new OrdenDeCompraPendiente();
        odcp.setVisible(true);
    }//GEN-LAST:event_btnPendientesActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        try {
            Clientes c = new Clientes();
            escritorio.add(c);
            c.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnGestionAlmacenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionAlmacenesActionPerformed
        try {
            String usuario = lblUsuario.getText();
            Almacenes a = new Almacenes(usuario);
            escritorio.add(a);
            a.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGestionAlmacenesActionPerformed

    private void btnTipoComprobantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoComprobantesActionPerformed
        try {
            TipoComprobantes tc = new TipoComprobantes();
            escritorio.add(tc);
            tc.setVisible(true);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }

    }//GEN-LAST:event_btnTipoComprobantesActionPerformed

    private void btnCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriasActionPerformed
        try {
            Categorias c = new Categorias(lblUsuario.getText());
            escritorio.add(c);
            c.setVisible(true);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnCategoriasActionPerformed

    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
        try {
            Proveedores p = new Proveedores(lblUsuario.getText());
            escritorio.add(p);
            p.setVisible(true);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnProveedoresActionPerformed

    private void btnMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovimientosActionPerformed
        try {
            String usuario = lblUsuario.getText();
            MovimientosAlmacen ma = new MovimientosAlmacen(usuario);
            escritorio.add(ma);
            ma.setVisible(true);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnMovimientosActionPerformed

    private void btnInsumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsumosActionPerformed
        try {
            String usuario = lblUsuario.getText();
            Insumos i = new Insumos(usuario);
            escritorio.add(i);
            i.setVisible(true);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnInsumosActionPerformed

    private void btnUsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMouseEntered
        if (!user) {
            Animacion.Animacion.mover_derecha(-50, 0, 1, 2, btnUsuarios);
        }
    }//GEN-LAST:event_btnUsuariosMouseEntered

    private void btnUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMouseExited
        if (!user) {
            Animacion.Animacion.mover_izquierda(0, -50, 1, 2, btnUsuarios);
        }
    }//GEN-LAST:event_btnUsuariosMouseExited

    private void btnPerfilesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerfilesMouseEntered
        if (!perfil) {
            Animacion.Animacion.mover_derecha(-50, 0, 1, 2, btnPerfiles);
        }
    }//GEN-LAST:event_btnPerfilesMouseEntered

    private void btnPerfilesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerfilesMouseExited
        if (!perfil) {
            Animacion.Animacion.mover_izquierda(0, -50, 1, 2, btnPerfiles);
        }
    }//GEN-LAST:event_btnPerfilesMouseExited

    private void btnPermisosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPermisosMouseEntered
        if (!permisos) {
            Animacion.Animacion.mover_derecha(-50, 0, 1, 2, btnPermisos);
        }
    }//GEN-LAST:event_btnPermisosMouseEntered

    private void btnPermisosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPermisosMouseExited
        if (!permisos) {
            Animacion.Animacion.mover_izquierda(0, -50, 1, 2, btnPermisos);
        }
    }//GEN-LAST:event_btnPermisosMouseExited

    private void btnConfiguracionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfiguracionMouseEntered
        if (!configuracion) {
            Animacion.Animacion.mover_derecha(-50, 0, 1, 2, btnConfiguracion);
        }
    }//GEN-LAST:event_btnConfiguracionMouseEntered

    private void btnConfiguracionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfiguracionMouseExited
        if (!configuracion) {
            Animacion.Animacion.mover_izquierda(0, -50, 1, 2, btnConfiguracion);
        }
    }//GEN-LAST:event_btnConfiguracionMouseExited

    private void btnAsistenciasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAsistenciasMouseEntered
        if (!asistencias) {
            Animacion.Animacion.mover_derecha(-50, 0, 1, 2, btnAsistencias);
        }
    }//GEN-LAST:event_btnAsistenciasMouseEntered

    private void btnAsistenciasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAsistenciasMouseExited
        if (!asistencias) {
            Animacion.Animacion.mover_izquierda(0, -50, 1, 2, btnAsistencias);
        }
    }//GEN-LAST:event_btnAsistenciasMouseExited

    private void btnPagosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagosMouseEntered
        if (!pagos) {
            Animacion.Animacion.mover_derecha(-50, 0, 1, 2, btnPagos);
        }
    }//GEN-LAST:event_btnPagosMouseEntered

    private void btnPagosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagosMouseExited
        if (!pagos) {
            Animacion.Animacion.mover_izquierda(0, -50, 1, 2, btnPagos);
        }
    }//GEN-LAST:event_btnPagosMouseExited

    private void btnClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseEntered
        if (!clientes) {
            Animacion.Animacion.mover_derecha(-50, 0, 1, 2, btnClientes);
        }
    }//GEN-LAST:event_btnClientesMouseEntered

    private void btnClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseExited
        if (!clientes) {
            Animacion.Animacion.mover_izquierda(0, -50, 1, 2, btnClientes);
        }
    }//GEN-LAST:event_btnClientesMouseExited

    private void btnReportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesMouseEntered
        if (!reportes) {
            Animacion.Animacion.mover_derecha(-50, 0, 1, 2, btnReportes);
        }
    }//GEN-LAST:event_btnReportesMouseEntered

    private void btnReportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesMouseExited
        if (!reportes) {
            Animacion.Animacion.mover_izquierda(0, -50, 1, 2, btnReportes);
        }
    }//GEN-LAST:event_btnReportesMouseExited

    private void btnMantenimientoVentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMantenimientoVentasMouseEntered
        if (!mantVentas) {
            Animacion.Animacion.mover_derecha(-50, 0, 1, 2, btnMantenimientoVentas);
        }
    }//GEN-LAST:event_btnMantenimientoVentasMouseEntered

    private void btnMantenimientoVentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMantenimientoVentasMouseExited
        if (!mantVentas) {
            Animacion.Animacion.mover_izquierda(0, -50, 1, 2, btnMantenimientoVentas);
        }
    }//GEN-LAST:event_btnMantenimientoVentasMouseExited

    private void btnOrdenCompraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrdenCompraMouseEntered
        if (!ordenCompra) {
            Animacion.Animacion.mover_derecha(-50, 0, 1, 2, btnOrdenCompra);
        }
    }//GEN-LAST:event_btnOrdenCompraMouseEntered

    private void btnOrdenCompraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrdenCompraMouseExited
        if (!ordenCompra) {
            Animacion.Animacion.mover_izquierda(0, -50, 1, 2, btnOrdenCompra);
        }
    }//GEN-LAST:event_btnOrdenCompraMouseExited

    private void btnPendientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPendientesMouseEntered
        if (!pendientes) {
            Animacion.Animacion.mover_derecha(-50, 0, 1, 2, btnPendientes);
        }
    }//GEN-LAST:event_btnPendientesMouseEntered

    private void btnPendientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPendientesMouseExited
        if (!pendientes) {
            Animacion.Animacion.mover_izquierda(0, -50, 1, 2, btnPendientes);
        }
    }//GEN-LAST:event_btnPendientesMouseExited

    private void btnProveedoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProveedoresMouseEntered
        if (!proveedores) {
            Animacion.Animacion.mover_derecha(-50, 0, 1, 2, btnProveedores);
        }
    }//GEN-LAST:event_btnProveedoresMouseEntered

    private void btnProveedoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProveedoresMouseExited
        if (!proveedores) {
            Animacion.Animacion.mover_izquierda(0, -50, 1, 2, btnProveedores);
        }
    }//GEN-LAST:event_btnProveedoresMouseExited

    private void btnContactosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContactosMouseEntered
        if (!contactos) {
            Animacion.Animacion.mover_derecha(-50, 0, 1, 2, btnContactos);
        }
    }//GEN-LAST:event_btnContactosMouseEntered

    private void btnContactosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContactosMouseExited
        if (!contactos) {
            Animacion.Animacion.mover_izquierda(0, -50, 1, 2, btnContactos);
        }
    }//GEN-LAST:event_btnContactosMouseExited

    private void btnGestionAlmacenesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionAlmacenesMouseEntered
        if (!gestionAlmacen) {
            Animacion.Animacion.mover_derecha(-50, 0, 1, 2, btnGestionAlmacenes);
        }
    }//GEN-LAST:event_btnGestionAlmacenesMouseEntered

    private void btnGestionAlmacenesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionAlmacenesMouseExited
        if (!gestionAlmacen) {
            Animacion.Animacion.mover_izquierda(0, -50, 1, 2, btnGestionAlmacenes);
        }
    }//GEN-LAST:event_btnGestionAlmacenesMouseExited

    private void btnCategoriasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCategoriasMouseEntered
        if (!categorias) {
            Animacion.Animacion.mover_derecha(-50, 0, 1, 2, btnCategorias);
        }
    }//GEN-LAST:event_btnCategoriasMouseEntered

    private void btnCategoriasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCategoriasMouseExited
        if (!categorias) {
            Animacion.Animacion.mover_izquierda(0, -50, 1, 2, btnCategorias);
        }
    }//GEN-LAST:event_btnCategoriasMouseExited

    private void btnProductosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductosMouseEntered
        if (!productos) {
            Animacion.Animacion.mover_derecha(-50, 0, 1, 2, btnProductos);
        }
    }//GEN-LAST:event_btnProductosMouseEntered

    private void btnProductosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductosMouseExited
        if (!productos) {
            Animacion.Animacion.mover_izquierda(0, -50, 1, 2, btnProductos);
        }
    }//GEN-LAST:event_btnProductosMouseExited

    private void btnInsumosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsumosMouseEntered
        if (!insumos) {
            Animacion.Animacion.mover_derecha(-50, 0, 1, 2, btnInsumos);
        }
    }//GEN-LAST:event_btnInsumosMouseEntered

    private void btnInsumosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsumosMouseExited
        if (!insumos) {
            Animacion.Animacion.mover_izquierda(0, -50, 1, 2, btnInsumos);
        }
    }//GEN-LAST:event_btnInsumosMouseExited

    private void btnMovimientosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMovimientosMouseEntered
        if (!movimientos) {
            Animacion.Animacion.mover_derecha(-50, 0, 1, 2, btnMovimientos);
        }
    }//GEN-LAST:event_btnMovimientosMouseEntered

    private void btnMovimientosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMovimientosMouseExited
        if (!movimientos) {
            Animacion.Animacion.mover_izquierda(0, -50, 1, 2, btnMovimientos);
        }
    }//GEN-LAST:event_btnMovimientosMouseExited

    private void btnComprobantesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprobantesMouseEntered
        if (!comprobantes) {
            Animacion.Animacion.mover_derecha(600, 0, 1, 2, btnComprobantes);
        }
    }//GEN-LAST:event_btnComprobantesMouseEntered

    private void btnComprobantesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprobantesMouseExited
        if (!comprobantes) {
            Animacion.Animacion.mover_izquierda(0, 600, 1, 2, btnComprobantes);
        }
    }//GEN-LAST:event_btnComprobantesMouseExited

    private void btnTipoComprobantesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTipoComprobantesMouseEntered
        if (!tipoComprobante) {
            Animacion.Animacion.mover_derecha(1670, 0, 1, 2, btnTipoComprobantes);
        }
    }//GEN-LAST:event_btnTipoComprobantesMouseEntered

    private void btnTipoComprobantesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTipoComprobantesMouseExited
        if (!tipoComprobante) {
            Animacion.Animacion.mover_izquierda(0, 1720, 1, 2, btnTipoComprobantes);
        }
    }//GEN-LAST:event_btnTipoComprobantesMouseExited

    private void btnCierreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCierreMouseEntered
        if (!cierre) {
            Animacion.Animacion.mover_derecha(1670, 0, 1, 2, btnCierre);
        }
    }//GEN-LAST:event_btnCierreMouseEntered

    private void btnCierreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCierreMouseExited
        if (!cierre) {
            Animacion.Animacion.mover_izquierda(0, 1720, 1, 2, btnCierre);
        }
    }//GEN-LAST:event_btnCierreMouseExited

    private void btnGastosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGastosMouseEntered
        if (!gastos) {
            Animacion.Animacion.mover_derecha(1670, 0, 1, 2, btnGastos);
        }
    }//GEN-LAST:event_btnGastosMouseEntered

    private void btnGastosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGastosMouseExited
        if (!gastos) {
            Animacion.Animacion.mover_izquierda(0, 1720, 1, 2, btnGastos);
        }
    }//GEN-LAST:event_btnGastosMouseExited

    private void btnFlujoCajaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFlujoCajaMouseEntered
        if (!flujoCaja) {
            Animacion.Animacion.mover_derecha(1670, 0, 1, 2, btnFlujoCaja);
        }
    }//GEN-LAST:event_btnFlujoCajaMouseEntered

    private void btnFlujoCajaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFlujoCajaMouseExited
        if (!flujoCaja) {
            Animacion.Animacion.mover_izquierda(0, 1720, 1, 2, btnFlujoCaja);
        }
    }//GEN-LAST:event_btnFlujoCajaMouseExited

    private void btnContactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContactosActionPerformed
        try {
            String usuario = lblUsuario.getText();
            Contactos c = new Contactos(usuario);
            escritorio.add(c);
            c.setVisible(true);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnContactosActionPerformed

    private void btnGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGastosActionPerformed
        try {
            String usuario = lblUsuario.getText();
            Gastos g = new Gastos(usuario);
            escritorio.add(g);
            g.setVisible(true);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnGastosActionPerformed

    private void btnPresentacionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPresentacionesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPresentacionesMouseEntered

    private void btnPresentacionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPresentacionesMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPresentacionesMouseExited

    private void btnPresentacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPresentacionesActionPerformed
        try {
            Presentaciones p = new Presentaciones(lblUsuario.getText());
            escritorio.add(p);
            p.setVisible(true);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnPresentacionesActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        try {
            Productos p = new Productos(lblUsuario.getText());
            escritorio.add(p);
            p.setVisible(true);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnMedidasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMedidasMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMedidasMouseEntered

    private void btnMedidasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMedidasMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMedidasMouseExited

    private void btnMedidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedidasActionPerformed
        try {
            String usuario = lblUsuario.getText();
            Medidas m = new Medidas(usuario);
            escritorio.add(m);
            m.setVisible(true);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }

    }//GEN-LAST:event_btnMedidasActionPerformed

    private void btnCierreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCierreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCierreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        Cajas c = new Cajas();
//        escritorio.add(c);
//        c.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            PagosPersonal pp = new PagosPersonal();
            escritorio.add(pp);
            pp.setVisible(true);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        PromocionesPrecios pp = new PromocionesPrecios();
        escritorio.add(pp);
        pp.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ReporteContadora r = new ReporteContadora();
        escritorio.add(r);                
        r.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsistencias;
    private javax.swing.JButton btnCategorias;
    private javax.swing.JButton btnCierre;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnComprobantes;
    private javax.swing.JButton btnConfiguracion;
    private javax.swing.JButton btnContactos;
    private javax.swing.JButton btnFlujoCaja;
    private javax.swing.JButton btnGastos;
    private javax.swing.JButton btnGestionAlmacenes;
    private javax.swing.JButton btnInsumos;
    private javax.swing.JButton btnMantenimientoVentas;
    private javax.swing.JButton btnMedidas;
    private javax.swing.JButton btnMovimientos;
    private javax.swing.JButton btnOrdenCompra;
    private javax.swing.JButton btnPagos;
    private javax.swing.JButton btnPendientes;
    private javax.swing.JButton btnPerfiles;
    private javax.swing.JButton btnPermisos;
    private javax.swing.JButton btnPresentaciones;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnProveedores;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnTipoComprobantes;
    private javax.swing.JButton btnUsuarios;
    public javax.swing.JDesktopPane escritorio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblCerrarSesion;
    public javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
