/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Cronometro;
import Controlador.ManejadorFechas;
import Controlador.OrdenDeCompraControl;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gaby
 */
public class OrdenDeCompra extends javax.swing.JInternalFrame {

    DefaultListModel modelo;
    DefaultTableModel modeloAdd;

    public OrdenDeCompra(String usuario) throws Exception {
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
        //setLocationRelativeTo(null);
        txtUsuario.setText(usuario);
        new OrdenDeCompraControl().cargarComboResponsable(cmbResponsable);
        new OrdenDeCompraControl().cargarComboProveedor(cmbProveedor);
        new OrdenDeCompraControl().cargarComboAlmacen(cmbAlmacen);
        new OrdenDeCompraControl().cargarComboMedidas(cmbMedida);
        new OrdenDeCompraControl().cargarListaProductos(listaProductos, modelo);
        new Cronometro().iniciarCronometro(txtHora);
        txtFecha.setText(new ManejadorFechas().getFechaActual());
        titulosTablaProductos();
    }
    
    public void titulosTablaProductos(){
        String titulos[] = {"PRODUCTO", "CANTIDAD"};
        modeloAdd = new DefaultTableModel(null, titulos);
        tblProductos.setModel(modeloAdd);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Productos = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSeleccionarProductos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        cmbMedida = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        txtCantidadProductos = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtProductos = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaProductos = new javax.swing.JList();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtAreaResponsable = new javax.swing.JTextField();
        txtCodigoResponsable = new javax.swing.JTextField();
        txtNombreResponsable = new javax.swing.JTextField();
        txtApellidoResponsable = new javax.swing.JTextField();
        txtDniResponsable = new javax.swing.JTextField();
        cmbResponsable = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        txtRuc = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtRazon = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        cmbProveedor = new javax.swing.JComboBox<>();
        txtCodigoProveedor = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        cmbAlmacen = new javax.swing.JComboBox();
        jTextField15 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jdcFechaFin = new com.toedter.calendar.JDateChooser();
        jLabel34 = new javax.swing.JLabel();
        cmbMoneda = new javax.swing.JComboBox();
        jdcFechaInicio = new com.toedter.calendar.JDateChooser();
        btnListarCompras = new javax.swing.JButton();
        btnRegCompra = new javax.swing.JButton();
        btnNuevaCompra = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        Productos.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblSeleccionarProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblSeleccionarProductos);

        Productos.getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 320));

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("ORDEN DE COMPRA");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INGRESAR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("CANTIDAD DE  PRODUCTO");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        jPanel1.add(cmbMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 170, -1));

        jLabel10.setText("UNIDAD DEL PRODUCTO");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));

        txtCantidadProductos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtCantidadProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 80, -1));

        jLabel33.setText("PRODUCTO");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        txtProductos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 230, -1));

        jScrollPane2.setViewportView(listaProductos);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 360, 120));

        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 113, 170, 60));

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProductos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 710, 190));
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 760, 410));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESPONSABLE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setText("AREA");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel15.setText("CÓDIGO");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel16.setText("NOMBRES");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel17.setText("APELLIDOS");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel18.setText("DNI");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        txtAreaResponsable.setEditable(false);
        txtAreaResponsable.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.add(txtAreaResponsable, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 310, -1));

        txtCodigoResponsable.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(txtCodigoResponsable, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 90, -1));

        txtNombreResponsable.setEditable(false);
        txtNombreResponsable.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.add(txtNombreResponsable, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 310, -1));

        txtApellidoResponsable.setEditable(false);
        txtApellidoResponsable.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.add(txtApellidoResponsable, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 310, -1));

        txtDniResponsable.setEditable(false);
        txtDniResponsable.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.add(txtDniResponsable, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 310, -1));

        cmbResponsable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NULL" }));
        cmbResponsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbResponsableActionPerformed(evt);
            }
        });
        jPanel3.add(cmbResponsable, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 210, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 420, 170));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PROVEEDOR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setText("CÓDIGO");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel20.setText("DIRECCION");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel21.setText("RUC");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        jLabel22.setText("E-MAIL");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel23.setText("TELEFONO");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        txtDireccion.setEditable(false);
        txtDireccion.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 320, -1));

        txtRuc.setEditable(false);
        txtRuc.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.add(txtRuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 150, -1));

        txtEmail.setEditable(false);
        txtEmail.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 320, -1));

        txtTelefono.setEditable(false);
        txtTelefono.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 130, -1));

        txtRazon.setEditable(false);
        txtRazon.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.add(txtRazon, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 320, -1));

        jLabel24.setText("RAZON S.");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        cmbProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NULL" }));
        cmbProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProveedorActionPerformed(evt);
            }
        });
        jPanel4.add(cmbProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 210, -1));

        txtCodigoProveedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(txtCodigoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 90, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 420, 170));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DOCUMENTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setText("ALMACEN");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        jLabel26.setText("FECHA FIN");
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        cmbAlmacen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NULL" }));
        jPanel5.add(cmbAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 170, -1));

        jTextField15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel5.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 70, -1));

        jLabel31.setText("N° ORDEN");
        jPanel5.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel32.setText("FECHA INICIO");
        jPanel5.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));
        jPanel5.add(jdcFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 140, -1));

        jLabel34.setText("MONEDA");
        jPanel5.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        cmbMoneda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "S/. SOL", "$ DOLAR", "€ EURO" }));
        jPanel5.add(cmbMoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 170, -1));
        jPanel5.add(jdcFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 140, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 570, 120));

        btnListarCompras.setText("LISTA DE ORDENES DE COMPRA");
        getContentPane().add(btnListarCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 760, 220, -1));

        btnRegCompra.setText("GENERAR ORDEN DE COMPRA");
        getContentPane().add(btnRegCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 700, 220, -1));

        btnNuevaCompra.setText("NUEVA ORDEN DE COMPRA");
        getContentPane().add(btnNuevaCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 730, 220, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("PRESUPUESTO ASIGNADO");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 430, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setText("S/.");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 450, -1, -1));

        jPanel8.setBackground(new java.awt.Color(102, 102, 102));
        jPanel8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("ORDEN DE COMPRA");
        jPanel8.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, 30));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carro-de-la-compra2.png"))); // NOI18N
        jPanel8.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 70));

        txtFecha.setEditable(false);
        txtFecha.setBackground(new java.awt.Color(102, 102, 102));
        txtFecha.setForeground(new java.awt.Color(255, 255, 255));
        txtFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFecha.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "FECHA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 8), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel8.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, 90, -1));

        txtHora.setEditable(false);
        txtHora.setBackground(new java.awt.Color(102, 102, 102));
        txtHora.setForeground(new java.awt.Color(255, 255, 255));
        txtHora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHora.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "HORA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 8), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel8.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 90, -1));

        txtUsuario.setEditable(false);
        txtUsuario.setBackground(new java.awt.Color(102, 102, 102));
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "USUARIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 8), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel8.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 140, -1));

        jLabel36.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        jLabel36.setText("ORDEN DE COMPRA");
        jPanel8.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 20, -1, 30));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 70));

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setBackground(new java.awt.Color(0, 0, 0));
        jLabel37.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 51, 0));
        jLabel37.setText("DISCOTECK");
        jPanel6.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, -1, -1));

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel13.setText("DISCOTECK");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(882, 0, -1, -1));

        jLabel38.setBackground(new java.awt.Color(0, 0, 0));
        jLabel38.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("MISTER JUERGA");
        jPanel6.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, -1, -1));

        jLabel39.setBackground(new java.awt.Color(0, 0, 0));
        jLabel39.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel39.setText("MISTER JUERGA");
        jPanel6.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(722, 0, -1, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 810, 1030, 40));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 480, 180, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String producto = listaProductos.getSelectedValue().toString();
        int cantidad = Integer.parseInt(txtCantidadProductos.getText());
        if (listaProductos.getSelectedIndex() >= 0 && !txtCantidadProductos.getText().trim().isEmpty()) {
            Object datos[] = {producto, cantidad};
            modeloAdd.addRow(datos);
        } else {
            JOptionPane.showMessageDialog(null, "DEBE SELECCIONAR UN PRODUCTO E INDICAR UNA CANTIDAD");
        }


    }//GEN-LAST:event_btnAgregarActionPerformed

    private void cmbResponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbResponsableActionPerformed
        try {
            String nom = cmbResponsable.getSelectedItem().toString();
            Object[] datos = (Object[]) new OrdenDeCompraControl().camposResponsableSeleccionado(nom);
            txtCodigoResponsable.setText("" + datos[0]);
            txtNombreResponsable.setText("" + datos[1]);
            txtApellidoResponsable.setText("" + datos[2]);
            txtDniResponsable.setText("" + datos[3]);
            txtAreaResponsable.setText("" + datos[4]);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_cmbResponsableActionPerformed

    private void cmbProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProveedorActionPerformed
        try {
            String prov = cmbProveedor.getSelectedItem().toString();
            Object[] datos = (Object[]) new OrdenDeCompraControl().camposProveedorSeleccionado(prov);
            txtCodigoProveedor.setText("" + datos[0]);
            txtRazon.setText("" + datos[1]);
            txtTelefono.setText("" + datos[2]);
            txtRuc.setText("" + datos[3]);
            txtEmail.setText("" + datos[4]);
            txtDireccion.setText("" + datos[5]);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_cmbProveedorActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(OrdenDeCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(OrdenDeCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(OrdenDeCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(OrdenDeCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                try {
//                    new OrdenDeCompra().setVisible(true);
//                } catch (Exception ex) {
//                    Logger.getLogger(OrdenDeCompra.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Productos;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnListarCompras;
    private javax.swing.JButton btnNuevaCompra;
    private javax.swing.JButton btnRegCompra;
    private javax.swing.JComboBox cmbAlmacen;
    private javax.swing.JComboBox cmbMedida;
    private javax.swing.JComboBox cmbMoneda;
    private javax.swing.JComboBox<String> cmbProveedor;
    private javax.swing.JComboBox<String> cmbResponsable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField15;
    private com.toedter.calendar.JDateChooser jdcFechaFin;
    private com.toedter.calendar.JDateChooser jdcFechaInicio;
    private javax.swing.JList listaProductos;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTable tblSeleccionarProductos;
    private javax.swing.JTextField txtApellidoResponsable;
    private javax.swing.JTextField txtAreaResponsable;
    private javax.swing.JTextField txtCantidadProductos;
    private javax.swing.JTextField txtCodigoProveedor;
    private javax.swing.JTextField txtCodigoResponsable;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDniResponsable;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtNombreResponsable;
    private javax.swing.JTextField txtProductos;
    private javax.swing.JTextField txtRazon;
    private javax.swing.JTextField txtRuc;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
