/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ProductoPresentacionControl;
import Controlador.Validaciones;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marce
 */
public class ProductoPresentacion extends javax.swing.JFrame {

    DefaultListModel modeloPresentacion = new DefaultListModel();
    DefaultTableModel dtm;

    public ProductoPresentacion() throws Exception {
        initComponents();
        setLocationRelativeTo(null);
        new ProductoPresentacionControl().llenarProductos(listaProductos);
        new ProductoPresentacionControl().cargarComboPresentacion(cmbPresentaciones);
        new ProductoPresentacionControl().cargarComboAlmacen(cmbAlmacen);
        new ProductoPresentacionControl().cargarComboCategoria(cmbCategoria);
        tablaProductoPresentacion();
        new ProductoPresentacionControl().LlenarTabla(tblProductoPresentacion, 50, 100, 200);
    }

    public void tablaProductoPresentacion() {
        String titulos[] = {"PRODUCTO", "CATEGORÍA", "PRESENTACION", "ALMACEN", "STOCK", "PRECIO"};
        dtm = new DefaultTableModel(null, titulos);
        tblProductoPresentacion.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaProductos = new javax.swing.JList<>();
        cmbPresentaciones = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblProductoPresentacion = new javax.swing.JTable();
        panelCabecera = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        lblSombra = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbAlmacen = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbCategoria = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(listaProductos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 140, 230));

        getContentPane().add(cmbPresentaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 170, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("AÑADIDOS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 90, -1));

        jLabel5.setText("PRECIO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 90, -1));

        btnAdd.setBackground(new java.awt.Color(0, 153, 0));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("+");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 170, 30));

        btnDel.setBackground(new java.awt.Color(255, 0, 0));
        btnDel.setForeground(new java.awt.Color(255, 255, 255));
        btnDel.setText("X");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        getContentPane().add(btnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 350, 60, -1));

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 390, 190, 40));

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 390, 190, 40));

        jLabel6.setText("PRESENTACION");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        tblProductoPresentacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblProductoPresentacion);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 710, 230));

        panelCabecera.setBackground(new java.awt.Color(255, 153, 102));
        panelCabecera.setForeground(new java.awt.Color(255, 255, 255));
        panelCabecera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("GESTION DE PRODUCTOS");
        panelCabecera.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, 30));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tienda-online.png"))); // NOI18N
        panelCabecera.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 70));

        txtFecha.setEditable(false);
        txtFecha.setBackground(new java.awt.Color(255, 153, 102));
        txtFecha.setForeground(new java.awt.Color(255, 255, 255));
        txtFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFecha.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "FECHA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 8), new java.awt.Color(255, 255, 255))); // NOI18N
        panelCabecera.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 20, 90, -1));

        txtHora.setEditable(false);
        txtHora.setBackground(new java.awt.Color(255, 153, 102));
        txtHora.setForeground(new java.awt.Color(255, 255, 255));
        txtHora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHora.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "HORA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 8), new java.awt.Color(255, 255, 255))); // NOI18N
        panelCabecera.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, 90, -1));

        txtUsuario.setEditable(false);
        txtUsuario.setBackground(new java.awt.Color(255, 153, 102));
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "USUARIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 8), new java.awt.Color(255, 255, 255))); // NOI18N
        panelCabecera.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 140, -1));

        lblSombra.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        lblSombra.setText("GESTION DE PRODUCTOS");
        lblSombra.setName(""); // NOI18N
        panelCabecera.add(lblSombra, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 20, -1, 30));

        getContentPane().add(panelCabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 70));

        jLabel1.setText("ALMACEN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        getContentPane().add(cmbAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 170, -1));

        jLabel2.setText("STOCK");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        txtStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStockKeyTyped(evt);
            }
        });
        getContentPane().add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 90, -1));

        jLabel3.setText("CATEGORIA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        getContentPane().add(cmbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 170, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("PRODUCTOS");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        //validar que este seleccionado un elemento de la lista de productos
        int filaProducto = listaProductos.getSelectedIndex();
        if (filaProducto >= 0) {
            if (new Validaciones().validarCampoVacio(txtStock)) {
                if (new Validaciones().validarCampoVacio(txtPrecio)) {
                    int flag = 0;
                    int numFilas = tblProductoPresentacion.getRowCount();
                    String producto = listaProductos.getSelectedValue();
                    String categoria = cmbCategoria.getSelectedItem().toString();
                    String presentacion = cmbPresentaciones.getSelectedItem().toString();
                    String almacen = cmbAlmacen.getSelectedItem().toString();
                    if (numFilas > 0) {
                        for (int i = 0; i < numFilas; i++) {
                            //System.out.println(i);
                            if (tblProductoPresentacion.getValueAt(i, 0).toString().equals(producto) && tblProductoPresentacion.getValueAt(i, 2).toString().equals(presentacion)) {
                                flag++;
                            }
                        }
                        if (flag > 0) {
                            JOptionPane.showMessageDialog(getRootPane(), "LA PRESENTACION " + presentacion + " DE " + producto + " YA ESTA SELECCIONADA");
                        } else {
                            //System.out.println("la presentacion " + presentacion + " se añadió");
                            String precio = txtPrecio.getText();
                            String stock = txtStock.getText();
                            Object datos[] = new Object[6];
                            datos[0] = producto;
                            datos[1] = categoria;
                            datos[2] = presentacion;
                            datos[3] = almacen;
                            datos[4] = stock;
                            datos[5] = precio;
                            dtm.addRow(datos);
                            tblProductoPresentacion.setModel(dtm);
                        }
                    } else {
                        //System.out.println("numero de filas: " + numFilas);
                        String precio = txtPrecio.getText();
                        String stock = txtStock.getText();
                        Object datos[] = new Object[6];
                        datos[0] = producto;
                        datos[1] = categoria;
                        datos[2] = presentacion;
                        datos[3] = almacen;
                        datos[4] = stock;
                        datos[5] = precio;
                        dtm.addRow(datos);
                        tblProductoPresentacion.setModel(dtm);
                    }
                } else {
                }
            } else {
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "SELECCIONE UN PRODUCTO DE LA LISTA");
        }
        //validar que los campos de texto stock y precio no esten vacios y tengan valores numericos

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        int filaSeleccionada = tblProductoPresentacion.getSelectedRow();
        if (filaSeleccionada >= 0) {
            dtm.removeRow(filaSeleccionada);
        } else {
            JOptionPane.showMessageDialog(getRootPane(), "SELECCIONE UN ELEMENTO DE LA TABLA A ELIMINAR");
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            //validar que la tabla tenga filas agregadas
            if (tblProductoPresentacion.getRowCount() >= 0) {
                //metodo para guardar los datos a la bd
                int numFilas = tblProductoPresentacion.getRowCount();
                for (int i = 0; i < numFilas; i++) {
                    String producto = tblProductoPresentacion.getValueAt(i, 0).toString();
                    String categoria = tblProductoPresentacion.getValueAt(i, 1).toString();
                    String presentacion = tblProductoPresentacion.getValueAt(i, 2).toString();
                    String almacen = tblProductoPresentacion.getValueAt(i, 3).toString();
                    int stock = Integer.parseInt(tblProductoPresentacion.getValueAt(i, 4).toString());
                    double precio = Double.parseDouble(tblProductoPresentacion.getValueAt(i, 5).toString());
                    if (new ProductoPresentacionControl().guardarGestionProducto(producto, categoria, presentacion, almacen, stock, precio) > 0) {
                        System.out.println("OK");
                    } else {
                        System.out.println("ERROR");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(getRootPane(), "AGREGUE ELEMENTOS A LA TABLA DE GESTION DE PRODUCTOS");
            }
            //metodo para limpiar si todo se opero correctamente
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockKeyTyped
        new Validaciones().validarCampoString(evt, txtStock);
    }//GEN-LAST:event_txtStockKeyTyped

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        new Validaciones().validarCampoString(evt, txtPrecio);
    }//GEN-LAST:event_txtPrecioKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductoPresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductoPresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductoPresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductoPresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ProductoPresentacion().setVisible(true);
                } catch (Exception ex) {
                    System.out.println(ex.getMessage());
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbAlmacen;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JComboBox<String> cmbPresentaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblSombra;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JList<String> listaProductos;
    private javax.swing.JPanel panelCabecera;
    private javax.swing.JTable tblProductoPresentacion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
