/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Validaciones;
import Modelo.Caja;
import Modelo.Conexion;
import Modelo.MySQLDAO.CajaDAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MARCEL
 */
public class ResumenCajas extends javax.swing.JInternalFrame {

    DefaultTableModel modelo;

    public ResumenCajas() {
        initComponents();
        titulos();
        cargarComboCajas();
    }

    public void titulos() {
        String titulos[] = {"COD", "CAJERA", "INICIO", "FIN", "INGRESOS", "EGRESOS", "IGV ACUMULADO"};
        modelo = new DefaultTableModel(null, titulos);
        tblResumen.setModel(modelo);
        tblResumen.getColumnModel().getColumn(0).setPreferredWidth(10);
        tblResumen.getColumnModel().getColumn(1).setPreferredWidth(100);
        tblResumen.getColumnModel().getColumn(2).setPreferredWidth(100);
        tblResumen.getColumnModel().getColumn(3).setPreferredWidth(100);
        tblResumen.getColumnModel().getColumn(4).setPreferredWidth(100);
        tblResumen.getColumnModel().getColumn(5).setPreferredWidth(100);
        tblResumen.getColumnModel().getColumn(6).setPreferredWidth(200);

    }

    public void resumenCajas(int mes, int caja) throws Exception {
        limpiarTablaSalidas();
        Object datos[] = new Object[7];
        Conexion c = new Conexion();
        c.conectar();
        Connection con = c.getConexion();
        try {
            PreparedStatement query = con.prepareStatement("select distinct flujocaja.idflujocaja, usuario.nombre, flujocaja.fecha_inicio, flujocaja.fecha_final, round(flujocaja.ingresos,2) as ingresos,round(flujocaja.egresos,2) as egresos, round(((flujocaja.ingresos/1.18)*0.18),2) as IGV\n"
                    + "	from venta\n"
                    + "	inner join flujocaja on venta.idflujocaja = flujocaja.idflujocaja\n"
                    + "	inner join usuario on venta.idusuario = usuario.idusuario\n"
                    + "	inner join caja on flujocaja.idcaja = caja.idcaja\n"
                    + "	where month(flujocaja.fecha) = ? and flujocaja.estado = 0 and flujocaja.idcaja = ?");
            query.setInt(1, mes);
            query.setInt(2, caja);
            ResultSet rs = query.executeQuery();
            while (rs.next()) {
                datos[0] = rs.getInt("flujocaja.idflujocaja");
                datos[1] = rs.getString("usuario.nombre");
                datos[2] = rs.getString("flujocaja.fecha_inicio");
                datos[3] = rs.getString("flujocaja.fecha_final");
                datos[4] = rs.getString("ingresos");
                datos[5] = rs.getString("egresos");
                datos[6] = rs.getString("IGV");
                modelo.addRow(datos);
            }
            tblResumen.setModel(modelo);
            //sumaDeSalidas();
            query.close();
            rs.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            c.cerrar();
        }
    }

    public void limpiarTablaSalidas() {
        for (int i = 0; i < tblResumen.getRowCount(); i++) {
            modelo.removeRow(i);
            i -= 1;
        }
    }

    public void cargarComboCajas() {
        try {
            CajaDAO mdao = new CajaDAO();
            for (Caja c : mdao.Listar()) {
                cmbCajas.addItem(c.getNomCaja());
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbCajas = new javax.swing.JComboBox<>();
        jmcMes = new com.toedter.calendar.JMonthChooser();
        btnMostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResumen = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIgv = new javax.swing.JTextField();
        txtIngresos = new javax.swing.JTextField();
        txtEgresos = new javax.swing.JTextField();

        setClosable(true);
        setTitle("RESUMEN DE CAJA");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        getContentPane().add(cmbCajas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, -1));
        getContentPane().add(jmcMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 110, -1));

        btnMostrar.setText("MOSTRAR");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 10, 150, -1));

        tblResumen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblResumen);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1010, 570));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("TOTAL IGV");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 710, 120, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("TOTAL INGRESOS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 650, 120, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("TOTAL EGRESOS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 680, 120, -1));
        getContentPane().add(txtIgv, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 700, 150, 30));
        getContentPane().add(txtIngresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 640, 150, 30));
        getContentPane().add(txtEgresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 670, 150, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        try {
            int mes = jmcMes.getMonth() + 1;
            System.out.println(mes);
            int idCaja = new CajaDAO().getIdCaja(cmbCajas.getSelectedItem().toString());
            System.out.println(idCaja);
            resumenCajas(mes, idCaja);
            totales();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnMostrarActionPerformed

    public void totales() {
        double ingresos = 0.0;
        double egresos = 0.0;
        double igv = 0.0;
        int numFilas = tblResumen.getRowCount();
        for (int i = 0; i < numFilas; i++) {
            ingresos += Double.parseDouble(tblResumen.getValueAt(i, 4).toString());
            egresos += Double.parseDouble(tblResumen.getValueAt(i, 5).toString());
            igv += Double.parseDouble(tblResumen.getValueAt(i, 6).toString());
        }
        txtIngresos.setText(""+ new Validaciones().Redondear(ingresos));
        txtEgresos.setText(""+ new Validaciones().Redondear(egresos));
        txtIgv.setText(""+ new Validaciones().Redondear(igv));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrar;
    private javax.swing.JComboBox<String> cmbCajas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JMonthChooser jmcMes;
    private javax.swing.JTable tblResumen;
    private javax.swing.JTextField txtEgresos;
    private javax.swing.JTextField txtIgv;
    private javax.swing.JTextField txtIngresos;
    // End of variables declaration//GEN-END:variables
}
