package Vista;

import Controlador.UsuariosControl;
import Controlador.Validaciones;
import Modelo.Perfil;
import Modelo.Usuario;
import Modelo.UsuarioDAO;
import Modelo.UsuarioPerfil;
import Modelo.UsuarioPerfilDAO;
import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Gaby
 */
public class Usuarios extends javax.swing.JInternalFrame {

    DefaultListModel listaModelo = new DefaultListModel();
    JFileChooser seleccionado = new JFileChooser();
    File archivo;
    byte[] bytesImg;
    int indice = 1;

    public Usuarios(String usuario) throws Exception {
        initComponents();
        //setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);
        new UsuariosControl().LlenarTablaUsuarios(tblUsuarios, 50, 100, 150);
        new UsuariosControl().llenarComboPerfil(cmbPerfiles);
        txtUsuario1.setText(usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        btnImprimir = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtRuc = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        txtUsuario1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnBuscarImagen = new javax.swing.JButton();
        lblPath = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaPerfiles = new javax.swing.JList<>();
        btnAddPerfil = new javax.swing.JButton();
        btnDelPerfil = new javax.swing.JButton();
        cmbPerfiles = new javax.swing.JComboBox<>();
        cmbEmail = new javax.swing.JCheckBox();
        cmbRuc = new javax.swing.JCheckBox();
        cmbTelefono = new javax.swing.JCheckBox();
        cmbDireccion = new javax.swing.JCheckBox();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("GESTION DE USUARIOS");
        setToolTipText("");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("PERFILES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, -1, -1));

        jLabel4.setText("NOMBRES *");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel5.setText("DNI *");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jLabel6.setText("TELEFONO");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        jLabel7.setText("DIRECCION");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, -1, -1));

        jLabel9.setText("USUARIO *");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jLabel10.setText("CONTRASEÑA *");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        txtId.setEditable(false);
        txtId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 60, -1));

        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 170, -1));

        txtApellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtApellido.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 170, -1));

        txtDni.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDni.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniActionPerformed(evt);
            }
        });
        getContentPane().add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 170, -1));

        txtTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTelefono.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtTelefono.setEnabled(false);
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 140, -1));

        txtDireccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDireccion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtDireccion.setEnabled(false);
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, 140, -1));

        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 170, -1));

        txtPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 170, -1));

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 770, 530));

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imprimir.png"))); // NOI18N
        btnImprimir.setBorder(null);
        btnImprimir.setBorderPainted(false);
        btnImprimir.setContentAreaFilled(false);
        btnImprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        getContentPane().add(btnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 630, 120, -1));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        btnGuardar.setBorder(null);
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 630, -1, 40));

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/actualizar.png"))); // NOI18N
        btnModificar.setBorder(null);
        btnModificar.setBorderPainted(false);
        btnModificar.setContentAreaFilled(false);
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 630, 120, 40));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        btnEliminar.setBorder(null);
        btnEliminar.setBorderPainted(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 630, 120, 40));

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo.png"))); // NOI18N
        btnNuevo.setBorder(null);
        btnNuevo.setBorderPainted(false);
        btnNuevo.setContentAreaFilled(false);
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 630, -1, 40));

        jLabel16.setText("RUC");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        txtRuc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRuc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtRuc.setEnabled(false);
        getContentPane().add(txtRuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 140, -1));

        jLabel17.setText("E-MAIL");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        txtEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtEmail.setEnabled(false);
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 530, 140, -1));

        jPanel8.setBackground(new java.awt.Color(255, 102, 51));
        jPanel8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("USUARIOS");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, 30));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hombre.png"))); // NOI18N
        jPanel8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 70));

        txtFecha.setEditable(false);
        txtFecha.setBackground(new java.awt.Color(255, 102, 51));
        txtFecha.setForeground(new java.awt.Color(255, 255, 255));
        txtFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFecha.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "FECHA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 8), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel8.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 20, 90, -1));

        txtHora.setEditable(false);
        txtHora.setBackground(new java.awt.Color(255, 102, 51));
        txtHora.setForeground(new java.awt.Color(255, 255, 255));
        txtHora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHora.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "HORA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 8), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel8.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 20, 90, -1));

        txtUsuario1.setEditable(false);
        txtUsuario1.setBackground(new java.awt.Color(255, 102, 51));
        txtUsuario1.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuario1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "USUARIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 8), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel8.add(txtUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 140, -1));

        jLabel19.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        jLabel19.setText("USUARIOS");
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 20, -1, 30));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 70));

        jPanel6.setBackground(new java.awt.Color(255, 102, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 51, 0));
        jLabel13.setText("DISCOTECK");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, -1, -1));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel11.setText("DISCOTECK");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(902, 0, -1, -1));

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("MISTER JUERGA");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, -1, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel8.setText("MISTER JUERGA");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(742, 0, -1, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 1080, 40));
        getContentPane().add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 160, 140));

        jLabel14.setText("APELLIDOS *");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        btnBuscarImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carpeta.png"))); // NOI18N
        btnBuscarImagen.setBorder(null);
        btnBuscarImagen.setBorderPainted(false);
        btnBuscarImagen.setContentAreaFilled(false);
        btnBuscarImagen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarImagenActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        lblPath.setText(".");
        getContentPane().add(lblPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 260, -1));

        jLabel3.setText("ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jScrollPane3.setViewportView(listaPerfiles);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 580, 130, 100));

        btnAddPerfil.setBackground(new java.awt.Color(51, 153, 0));
        btnAddPerfil.setText("+");
        btnAddPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPerfilActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 610, -1, -1));

        btnDelPerfil.setBackground(new java.awt.Color(255, 102, 102));
        btnDelPerfil.setText("-");
        btnDelPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelPerfilActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, -1, -1));

        getContentPane().add(cmbPerfiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 130, -1));

        cmbEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEmailActionPerformed(evt);
            }
        });
        getContentPane().add(cmbEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, -1, -1));

        cmbRuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRucActionPerformed(evt);
            }
        });
        getContentPane().add(cmbRuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, -1, -1));

        cmbTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(cmbTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, -1, -1));

        cmbDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDireccionActionPerformed(evt);
            }
        });
        getContentPane().add(cmbDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
        try {
            int fila = tblUsuarios.getSelectedRow();
            int id = Integer.parseInt(tblUsuarios.getValueAt(fila, 0).toString());
            Object[] datos = new UsuariosControl().capturarDatosDeTabla(tblUsuarios, id);
            txtId.setText("" + datos[0]);
            txtNombre.setText("" + datos[1]);
            txtApellido.setText("" + datos[2]);
            txtDni.setText("" + datos[3]);
            txtTelefono.setText("" + datos[4]);
            txtDireccion.setText("" + datos[5]);
            txtUsuario.setText("" + datos[6]);
            txtPass.setText("" + datos[7]);
//            int fila = tblUsuarios.getSelectedRow();
//            int idprod = Integer.parseInt(tblUsuarios.getValueAt(fila, 0).toString())-1;
//            UsuarioDAO udao = new UsuarioDAO();
//            Usuario u = udao.listar().get(idprod);
//            txtId.setText(""+u.getId());
//            txtNombre.setText(u.getNombre());
//            txtApellido.setText(u.getApellido());
//            txtDni.setText(u.getDni());
//            txtTelefono.setText(u.getTelefono());
//            txtDireccion.setText(u.getDireccion());
//            txtImagen.setText(u.getImagen());
//            txtUsuario.setText(u.getUsuario());
//            txtPass.setText(u.getPass());            
//            Area a = new Area();
//            a.setIdarea(u.getIdArea());
//            cmbArea.setSelectedIndex(a.getIdarea()-1);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_tblUsuariosMouseClicked

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        lblImagen.setIcon(null);
        txtId.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtDni.setText("");
        txtTelefono.setText("");
        txtDireccion.setText("");
        lblPath.setText(".");
        txtUsuario.setText("");
        txtPass.setText("");
        tblUsuarios.clearSelection();
        listaModelo.removeAllElements();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        //VALIDACIONES
        Validaciones v = new Validaciones();
        if (v.validarCampoVacio(txtNombre)) {
            if (v.validarCampoVacio(txtApellido)) {
                if (v.validarCampoVacio(txtDni)) {
                    if (v.validarCampoVacio(txtUsuario)) {
                        if (v.validarCampoVacio(txtPass)) {
                            try {
                                Usuario u = new Usuario();
                                Perfil p = new Perfil();
                                u.setNombre(txtNombre.getText().toUpperCase());
                                u.setApellido(txtApellido.getText().toUpperCase());
                                u.setDni(txtDni.getText());
                                u.setRuc(txtRuc.getText());
                                u.setTelefono(txtTelefono.getText());
                                u.setDireccion(txtDireccion.getText().toUpperCase());
                                u.setImagen(txtDireccion.getText().toUpperCase());
                                u.setUsuario(txtUsuario.getText().toUpperCase());
                                u.setPass(txtPass.getText().toUpperCase());
                                if (!new UsuariosControl().verificarUsuario(u)) {
                                    UsuarioDAO udao = new UsuarioDAO();
                                    if (udao.registrar(u)) {
                                        System.out.println("SE REGISTRO EL USUARIO");
                                        for (int i = 0; i < listaPerfiles.getModel().getSize(); i++) {
                                            try {
                                                //obtener el id de los perfiles agregados
                                                p.setDescripcion(String.valueOf(listaModelo.getElementAt(i)));
                                                int idPerfil = new UsuariosControl().getIdPerfil(p);
                                                //obtener el ultimo id de usuario registrado
                                                int ultimoId = new UsuariosControl().getUltimoIdUsuario();
                                                //registrar en la tabla usuarioPerfil
                                                UsuarioPerfil up = new UsuarioPerfil();
                                                up.setIdusuario(ultimoId);
                                                up.setIdperfil(idPerfil);
                                                UsuarioPerfilDAO updao = new UsuarioPerfilDAO();
                                                if (updao.registrar(up)) {
                                                    System.out.println("SE REGISTRO PERFIL DE USUARIO");
                                                } else {
                                                    System.out.println("ERROR DE REGISTRO");
                                                }
                                            } catch (Exception ex) {
                                                System.out.println(ex.getMessage());
                                            }
                                        }
                                        new UsuariosControl().RefrescarTablaArea(tblUsuarios);
                                    } else {
                                        System.out.println("ERROR");
                                    }
                                } else {
                                    JOptionPane.showMessageDialog(null, "EL NOMBRE DE USUARIO INGRESADO YA EXISTE, INGRESE OTRO POR FAVOR");
                                    txtUsuario.requestFocus();
                                }
                            } catch (Exception ex) {
                                System.out.println(ex.getMessage());
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "INGRESE INGRESE CONTRASEÑA");
                            txtPass.requestFocus();
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "INGRESE USUARIO");
                        txtUsuario.requestFocus();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "INGRESE DNI");
                    txtDni.requestFocus();
                }

            } else {
                JOptionPane.showMessageDialog(null, "INGRESE APELLIDO");
                txtApellido.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(null, "INGRESE NOMBRE");
            txtNombre.requestFocus();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed

    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnBuscarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarImagenActionPerformed
        if (seleccionado.showDialog(null, "ABRIR ARCHIVO") == JFileChooser.APPROVE_OPTION) {
            archivo = seleccionado.getSelectedFile();
            if (archivo.canRead()) {
                if (archivo.getName().endsWith(".png") || archivo.getName().endsWith(".jpg") || archivo.getName().endsWith(".gif") || archivo.getName().endsWith(".jpeg")) {
                    try {
                        String p = archivo.getPath();
                        lblPath.setText(p);
                        ImageIcon imagen = new ImageIcon(p);
                        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), Image.SCALE_DEFAULT));
                        lblImagen.setIcon(icono);
                        lblImagen.repaint();
//                        bytesImg = new UsuariosControl().AbrirImagen(archivo);
//                        lblImagen.setIcon(new ImageIcon(bytesImg));
                    } catch (Exception ex) {
                        System.out.println(ex.getMessage());
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "SELECCIONE UN TIPO DE ARCHIVO VALIDO: png, jpg, jpeg, gif");
                }
            }
        }
    }//GEN-LAST:event_btnBuscarImagenActionPerformed

    private void btnAddPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPerfilActionPerformed
        try {
            System.out.println("");
            listaModelo.addElement(cmbPerfiles.getSelectedItem());
            listaPerfiles.setModel(listaModelo);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnAddPerfilActionPerformed

    private void btnDelPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelPerfilActionPerformed
        int numLista = listaPerfiles.getSelectedIndex();
        listaModelo.removeElementAt(numLista);
    }//GEN-LAST:event_btnDelPerfilActionPerformed

    private void cmbRucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRucActionPerformed
        if (cmbRuc.isSelected()) {
            txtRuc.setEnabled(true);
        } else {
            txtRuc.setEnabled(false);
        }
    }//GEN-LAST:event_cmbRucActionPerformed

    private void cmbTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTelefonoActionPerformed
        if (cmbTelefono.isSelected()) {
            txtTelefono.setEnabled(true);
        } else {
            txtTelefono.setEnabled(false);
        }
    }//GEN-LAST:event_cmbTelefonoActionPerformed

    private void cmbDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDireccionActionPerformed
        if (cmbDireccion.isSelected()) {
            txtDireccion.setEnabled(true);
        } else {
            txtDireccion.setEnabled(false);
        }
    }//GEN-LAST:event_cmbDireccionActionPerformed

    private void cmbEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEmailActionPerformed
        if (cmbEmail.isSelected()) {
            txtEmail.setEnabled(true);
        } else {
            txtEmail.setEnabled(false);
        }
    }//GEN-LAST:event_cmbEmailActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        txtApellido.requestFocus();
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        txtDni.requestFocus();
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniActionPerformed
        txtUsuario.requestFocus();
    }//GEN-LAST:event_txtDniActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        txtPass.requestFocus();
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try {
            //SETEANDO LOS PARAMETROS DE OBJETO USUARIO A MODIFICAR
            Usuario u = new Usuario();
            u.setNombre(txtNombre.getText().toUpperCase());
            u.setApellido(txtApellido.getText().toUpperCase());
            u.setDni(txtDni.getText());
            u.setRuc(txtRuc.getText());
            u.setTelefono(txtTelefono.getText());
            u.setDireccion(txtDireccion.getText().toUpperCase());
            u.setImagen(lblPath.getText().toUpperCase());
            u.setUsuario(txtUsuario.getText().toUpperCase());
            u.setPass(txtPass.getText().toUpperCase());
            u.setId(Integer.parseInt(txtId.getText()));
            //REGISTRAR MODIFICACION
            UsuarioDAO udao = new UsuarioDAO();
            if (udao.modificar(u)) {
                JOptionPane.showMessageDialog(null, "USUARIO MODIFICADO");
                new UsuariosControl().RefrescarTablaArea(tblUsuarios);
            } else {
                JOptionPane.showMessageDialog(null, "ERROR EN MODIFICACION");
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                try {
//                    new Usuarios().setVisible(true);
//                } catch (Exception ex) {
//                    Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPerfil;
    private javax.swing.JButton btnBuscarImagen;
    private javax.swing.JButton btnDelPerfil;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JCheckBox cmbDireccion;
    private javax.swing.JCheckBox cmbEmail;
    private javax.swing.JComboBox<String> cmbPerfiles;
    private javax.swing.JCheckBox cmbRuc;
    private javax.swing.JCheckBox cmbTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblPath;
    private javax.swing.JList<String> listaPerfiles;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtRuc;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtUsuario1;
    // End of variables declaration//GEN-END:variables
}
