/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Almacen;
import Modelo.Conexion;
import Modelo.MySQLDAO.AlmacenDAO;
import Modelo.MySQLDAO.ProductoPresentacionDAO;
import Modelo.MySQLDAO.ProductoRequerimientoDAO;
import Modelo.MySQLDAO.RequerimientoDAO;
import Modelo.MySQLDAO.UsuarioDAO;
import Modelo.Requerimiento;
import java.sql.Connection;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MARCEL
 */
public class ValidarRequerimiento extends javax.swing.JInternalFrame {

    DefaultTableModel modeloProductos;
    Almacen a = null;

    /**
     * Creates new form ValidarRequerimiento
     */
    public ValidarRequerimiento(String usuario) {
        initComponents();
        txtUsuario.setText(usuario);
        cargarTitulosProductos();
    }

    public void cargarTitulosProductos() {
        String cabeceraAdd[] = {"ID", "PRODUCTO", "PRESENTACION", "MEDIDA", "CANTIDAD"};
        modeloProductos = new DefaultTableModel(null, cabeceraAdd);
        tblProductos.setModel(modeloProductos);
    }

    public void LimpiarTabla() {
        for (int i = 0; i < tblProductos.getRowCount(); i++) {
            modeloProductos.removeRow(i);
            i -= 1;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtFechaEntrada = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnConfirmarRequerimiiento = new javax.swing.JButton();
        txtNumRequerimiento = new javax.swing.JTextField();
        txtUsuarioRequerimiento = new javax.swing.JTextField();
        txtDestino = new javax.swing.JTextField();
        txtFechaRequerimiento = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        txtHoraRequerimiento = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("VALIDACION DE REQUERIMIENTOS");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 40));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 840, 10));

        jLabel22.setText("USUARIO");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, -1, -1));

        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, 110, -1));

        jLabel23.setText("FECHA");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 600, -1, -1));

        txtFechaEntrada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFechaEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaEntradaActionPerformed(evt);
            }
        });
        getContentPane().add(txtFechaEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 600, 100, -1));

        txtEstado.setEditable(false);
        txtEstado.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        txtEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 240, -1));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("DESTINO");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 210, 20));

        jLabel10.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("USUARIO");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 210, 20));

        jLabel11.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("PRODUCTOS");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 140, 20));

        jLabel12.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("ESTADO");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 210, 20));

        jLabel13.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("FECHA");
        jPanel7.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 210, 20));

        jLabel3.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NUMERO DE REQUERIMIENTO");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        jLabel14.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("HORA");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 210, 20));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 240, 540));

        btnConfirmarRequerimiiento.setBackground(new java.awt.Color(102, 102, 102));
        btnConfirmarRequerimiiento.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        btnConfirmarRequerimiiento.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmarRequerimiiento.setText("CONFIRMAR REQUERIMIENTO");
        btnConfirmarRequerimiiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarRequerimiientoActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmarRequerimiiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 540, 250, -1));

        txtNumRequerimiento.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        txtNumRequerimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumRequerimientoActionPerformed(evt);
            }
        });
        getContentPane().add(txtNumRequerimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 110, -1));

        txtUsuarioRequerimiento.setEditable(false);
        txtUsuarioRequerimiento.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        txtUsuarioRequerimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioRequerimientoActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuarioRequerimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 240, -1));

        txtDestino.setEditable(false);
        txtDestino.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        txtDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDestinoActionPerformed(evt);
            }
        });
        getContentPane().add(txtDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 240, -1));

        txtFechaRequerimiento.setEditable(false);
        txtFechaRequerimiento.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        txtFechaRequerimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaRequerimientoActionPerformed(evt);
            }
        });
        getContentPane().add(txtFechaRequerimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 240, -1));

        tblProductos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tblProductos.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 14)); // NOI18N
        tblProductos.setForeground(new java.awt.Color(51, 51, 51));
        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProductos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 570, 260));

        txtHoraRequerimiento.setEditable(false);
        txtHoraRequerimiento.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        txtHoraRequerimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraRequerimientoActionPerformed(evt);
            }
        });
        getContentPane().add(txtHoraRequerimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 240, -1));

        btnBuscar.setBackground(new java.awt.Color(102, 102, 102));
        btnBuscar.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 120, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFechaEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaEntradaActionPerformed

    private void txtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoActionPerformed

    private void btnConfirmarRequerimiientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarRequerimiientoActionPerformed
        int idAlmacen = a.getId();
        try {
            sumarStock(idAlmacen);
            restarStock(1);//se quita los productos de almacen principal (1)
            RequerimientoDAO rdao = new RequerimientoDAO();
            rdao.Confirmar(Integer.parseInt(txtNumRequerimiento.getText()));
            
            limpiar();
        } catch (Exception ex) {
            Logger.getLogger(ValidarRequerimiento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConfirmarRequerimiientoActionPerformed

    private void txtNumRequerimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumRequerimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumRequerimientoActionPerformed

    private void txtUsuarioRequerimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioRequerimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioRequerimientoActionPerformed

    private void txtDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDestinoActionPerformed

    private void txtFechaRequerimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaRequerimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaRequerimientoActionPerformed

    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseClicked
        if (evt.getClickCount() == 2) {

        }
    }//GEN-LAST:event_tblProductosMouseClicked

    private void txtHoraRequerimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraRequerimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraRequerimientoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int idRequerimiento = Integer.parseInt(txtNumRequerimiento.getText());
        try {

            if (!txtNumRequerimiento.getText().trim().isEmpty()) {

                LimpiarTabla();

                RequerimientoDAO rdao = new RequerimientoDAO();
                Requerimiento r = new Requerimiento();

                r = rdao.Obtener(idRequerimiento);

                UsuarioDAO udao = new UsuarioDAO();
                AlmacenDAO adao = new AlmacenDAO();
                a = adao.Obtener(r.getIdAlmacen());

                txtUsuarioRequerimiento.setText("" + udao.Obtener(r.getIdUsuario()).getNombre());
                txtDestino.setText("" + a.getNombre());
                txtFechaRequerimiento.setText(r.getFecha());
                txtHoraRequerimiento.setText(r.getHora());
                txtEstado.setText("" + r.getEstado());

                ProductoRequerimientoDAO prdao = new ProductoRequerimientoDAO();

                Object datos[] = new Object[5];

                int numFilas = prdao.Listar(idRequerimiento).size();

                for (int i = 0; i < numFilas; i++) {
                    datos[0] = prdao.Listar(idRequerimiento).get(i).getIdProducto();
                    datos[1] = prdao.Listar(idRequerimiento).get(i).getProducto();
                    datos[2] = prdao.Listar(idRequerimiento).get(i).getPresentacion();
                    datos[3] = prdao.Listar(idRequerimiento).get(i).getMedida();
                    datos[4] = prdao.Listar(idRequerimiento).get(i).getCantidad();

                    modeloProductos.addRow(datos);
                }

                tblProductos.setModel(modeloProductos);

            } else {
                JOptionPane.showMessageDialog(getRootPane(), "INGRESE NUMERO DE REQUERIMIENTO");
                txtNumRequerimiento.requestFocus();
            }

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void limpiar() {
        txtNumRequerimiento.setText("");
        txtUsuarioRequerimiento.setText("");
        txtDestino.setText("");
        txtFechaRequerimiento.setText("");
        txtHoraRequerimiento.setText("");
        txtEstado.setText("");
        LimpiarTabla();
        txtNumRequerimiento.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnConfirmarRequerimiiento;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtFechaEntrada;
    private javax.swing.JTextField txtFechaRequerimiento;
    private javax.swing.JTextField txtHoraRequerimiento;
    private javax.swing.JTextField txtNumRequerimiento;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtUsuarioRequerimiento;
    // End of variables declaration//GEN-END:variables

    private void sumarStock(int idAlmacen) throws Exception {
        Conexion c = new Conexion();
        c.conectar();
        Connection con = c.getConexion();
        int numFilas = tblProductos.getRowCount();
        try {
            Statement st = null;
            for (int i = 0; i < numFilas; i++) {
                int id = Integer.parseInt(tblProductos.getValueAt(i, 0).toString());
                System.out.println("id: " + id);
                double cantidad = Double.parseDouble(tblProductos.getValueAt(i, 4).toString());
                System.out.println("cantidad: " + cantidad);
                double stock = new ProductoPresentacionDAO().Obtener(id, idAlmacen).getStock();
                System.out.println("stock: " + stock);
                double newStock = stock + cantidad;
                System.out.println("stock: " + newStock);
                String sql = "UPDATE productopresentacion SET stock = " + newStock + " WHERE idproducto = " + id + " AND idalmacen = " + idAlmacen + "";

                st = con.createStatement();
                int rs = st.executeUpdate(sql);
                if (rs > 0) {
                    System.out.println("Se actualizo en stock del producto :" + id);
                }
            }
            st.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            con.close();
            c.cerrar();
        }
    }
    
    
    private void restarStock(int idAlmacen) throws Exception {
        Conexion c = new Conexion();
        c.conectar();
        Connection con = c.getConexion();
        int numFilas = tblProductos.getRowCount();
        try {
            Statement st = null;
            for (int i = 0; i < numFilas; i++) {
                int id = Integer.parseInt(tblProductos.getValueAt(i, 0).toString());
                System.out.println("id: " + id);
                double cantidad = Double.parseDouble(tblProductos.getValueAt(i, 4).toString());
                System.out.println("cantidad: " + cantidad);
                double stock = new ProductoPresentacionDAO().Obtener(id, idAlmacen).getStock();
                System.out.println("stock: " + stock);
                double newStock = stock - cantidad;
                System.out.println("stock: " + newStock);
                String sql = "UPDATE `productopresentacion` SET `stock`=" + newStock + " WHERE `idproducto` = " + id + " AND idalmacen = " + idAlmacen + "";
                st = con.createStatement();
                int rs = st.executeUpdate(sql);
                if (rs > 0) {
                    System.out.println("Se actualizo en stock del producto :" + id);
                }
            }
            st.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally{
            con.close();
            c.cerrar();
        }
    }

}
